--[[
	"Abomination" = 
	"Akil'zon" = 
	"Amani Dragonhawk" = 
	"Amani Elder Lynx" = 
	"Amani'shi Axe Thrower" = 
	"Amani'shi Beast Tamer" = 
	"Amani'shi Guardian" = 
	"Amani'shi Handler" = 
	"Amani'shi Scout" = 
	"Amani'shi Tribesman" = 
	"Amani'shi Warbringer" = 
	"Amani'shi Wind Walker" = 
	"Anetheron" = 
	"Anguished Dead" = 
	"Anvilrage Captain" = 
	"Anvilrage Marshal" = 
	"Anvilrage Overseer" = 
	"Anvilrage Soldier" = 
	"Apocalypse Guard" = 
	"Arcane Anomaly" = 
	"Arcane Protector" = 
	"Arcatraz Sentinel" = 
	"Archimonde" = 
	"Atal'ai Deathwalker" = 
	"Atal'ai Warrior" = 
	"Atal'ai Witch Doctor" = 
	"Attumen the Huntsman" = 
	"Auchenai Monk" = 
	"Ayamiss the Hunter" = 
	"Azgalor" = 
	"Bannok Grimaxe" = 
	"Banshee" = 
	"Baron Geddon" = 
	"Battleguard Sartura" = 
	"Blackhand Elite" = 
	"Blackheart the Inciter" = 
	"Bleeding Hollow Darkcaster" = 
	"Bloodhound" = 
	"Bloodwarder Legionnaire" = 
	"Bloodwarder Vindicator" = 
	"Bog Giant" = 
	"Bonechewer Destroyer" = 
	"Burrowing Thundersnout" = 
	"Buru the Gorger" = 
	"Cabal Acolyte" = 
	"Cabal Cultist" = 
	"Cabal Fanatic" = 
	"Cabal Spellbinder" = 
	"Cannon Master Willey" = 
	"Captain Skarloc" = 
	"Cataclysm Hound" = 
	"Chrono Lord Deja" = 
	"Cobalt Serpent" = 
	"Coilfang Champion" = 
	"Coilfang Hate-Screamer" = 
	"Coilfang Myrmidon" = 
	"Coilfang Oracle" = 
	"Coilfang Serpentguard" = 
	"Coilfang Shatterer" = 
	"Coilfang Siren" = 
	"Coilfang Sorceress" = 
	"Coilfang Technician" = 
	"Coilfang Warrior" = 
	"Coilskar Sea-Caller" = 
	"Commander Sarannis" = 
	"Crimson Inquisitor" = 
	"Crimson Sorcerer" = 
	"Crypt Fiend" = 
	"Crystalcore Mechanic" = 
	"Dalliah the Doomsayer" = 
	"Dark Screecher" = 
	"Darkmaster Gandling" = 
	"Darkwater Crocolisk" = 
	"Darkweaver Syth" = 
	"Deep Stinger" = 
	"Defias Pirate" = 
	"Defias Squallshaper" = 
	"Don Carlos" = 
	"Doomfire Destroyer" = 
	"Doomforge Craftsman" = 
	"Doomforge Dragoon" = 
	"Dragonmaw Wind Reaver" = 
	"Durnholde Lookout" = 
	"Durnholde Rifleman" = 
	"Durnholde Tracking Hound" = 
	"Emperor Vek'lor" = 
	"Emperor Vek'nilash" = 
	"Epoch Hunter" = 
	"Eredar Deathbringer" = 
	"Ethereal Priest" = 
	"Ethereal Scavenger" = 
	"Ethereal Spellbinder" = 
	"Ethereal Thief" = 
	"Ethereum Smuggler" = 
	"Exarch Maladaar" = 
	"Fankriss the Unyielding" = 
	"Fel Orc Convert" = 
	"Fel Rager" = 
	"Fel Stalker" = 
	"Felguard Annihilator" = 
	"Firebrand Grunt" = 
	"Firebrand Invoker" = 
	"Firebrand Legionnaire" = 
	"Firebrand Pyromancer" = 
	"Fleshbeast" = 
	"Frost Wyrm" = 
	"Gargantuan Abyssal" = 
	"Gargoyle" = 
	"Garr" = 
	"Gehennas" = 
	"General Drakkisath" = 
	"General Rajaxx" = 
	"Ghaz'an" = 
	"Ghostly Philanthropist" = 
	"Ghostly Steward" = 
	"Ghoul" = 
	"Giant Infernal" = 
	"Golem Lord Argelmach" = 
	"Golemagg the Incinerator" = 
	"Goraluk Anvilcrack" = 
	"Grand Warlock Nethekurse" = 
	"Greater Bogstrok" = 
	"Greater Fleshbeast" = 
	"Grizzle" = 
	"Gronn-Priest" = 
	"Halazzi" = 
	"Hammered Patron" = 
	"Hex Lord Malacrass" = 
	"High Botanist Freywinn" = 
	"Homunculus" = 
	"Hydromancer Thespia" = 
	"Ironbark Protector" = 
	"Jan'alai" = 
	"Kaz'rogal" = 
	"Kurinnaxx" = 
	"Lord Kazzak" = 
	"Lord Kri" = 
	"Lord Roccor" = 
	"Loro" = 
	"Lucifron" = 
	"Magical Horror" = 
	"Magister Kalendris" = 
	"Magmadar" = 
	"Maleki the Pallid" = 
	"Mana Warp" = 
	"Mechano-Lord Capacitus" = 
	"Mekgineer Steamrigger" = 
	"Mekgineer Thermaplugg" = 
	"Mennu the Betrayer" = 
	"Midnight" = 
	"Mijan" = 
	"Moam" = 
	"Moroes" = 
	"Murk Worm" = 
	"Murmur" = 
	"Nalorakk" = 
	"Nethermancer Sepethrea" = 
	"Nethervine Inciter" = 
	"Nexus Stalker" = 
	"Nexus-Prince Shaffar" = 
	"Nightbane" = 
	"Oblivion Mage" = 
	"Onyxia" = 
	"Ossirian the Unscarred" = 
	"Ouro" = 
	"Painbringer" = 
	"Pathaleon the Calculator" = 
	"Phantom Attendant" = 
	"Phantom Guardsman" = 
	"Phantom Guest" = 
	"Phantom Stagehand" = 
	"Phantom Valet" = 
	"Phoenix-Hawk" = 
	"Phoenix-Hawk Hatchling" = 
	"Plugger Spazzring" = 
	"Priestess Delrissa" = 
	"Priestess of Torment" = 
	"Princess Huhuran" = 
	"Princess Yauj" = 
	"Pusillin" = 
	"Pyromancer Loregrain" = 
	"Quartermaster Zigris" = 
	"Rabid Warhound" = 
	"Rage Talon Dragon Guard" = 
	"Rage Winterchill" = 
	"Raging Skeleton" = 
	"Ribbly Screwspigot" = 
	"Ribbly's Crony" = 
	"Rift Keeper" = 
	"Rift Lord" = 
	"Risen Bonewarder" = 
	"Risen Construct" = 
	"Sable Jaguar" = 
	"Sandfury Blood Drinker" = 
	"Sandfury Shadowcaster" = 
	"Scarlet Adept" = 
	"Scarlet Centurion" = 
	"Scarlet Gallant" = 
	"Scarlet Monk" = 
	"Scarlet Protector" = 
	"Scholomance Adept" = 
	"Scholomance Necromancer" = 
	"Serpentshrine Sporebat" = 
	"Sethekk Initiate" = 
	"Sethekk Prophet" = 
	"Sethekk Ravenguard" = 
	"Shade of Aran" = 
	"Shadow Pillager" = 
	"Shadowforge Peasant" = 
	"Shadowmoon Reaver" = 
	"Shadowsword Assassin" = 
	"Shadowsword Guardian" = 
	"Shadowsword Vanquisher" = 
	"Shadowy Necromancer" = 
	"Shattered Hand Centurion" = 
	"Shattered Hand Reaver" = 
	"Shazzrah" = 
	"Shrike Bat" = 
	"Skeletal Usher" = 
	"Solakar Flamewreath" = 
	"Sorcerous Shade" = 
	"Spawn of Hakkar" = 
	"Spectral Charger" = 
	"Spectral Performer" = 
	"Spectral Researcher" = 
	"Spectral Servant" = 
	"Spectral Stable Hand" = 
	"Spectral Stallion" = 
	"Spell Shade" = 
	"Spirestone Warlord" = 
	"Splinterbone Centurion" = 
	"Stonevault Oracle" = 
	"Stonevault Pillager" = 
	"Sunblade Arch Mage" = 
	"Sunblade Blood Knight" = 
	"Sunblade Cabalist" = 
	"Sunblade Dawn Priest" = 
	"Sunblade Dusk Priest" = 
	"Sunblade Mage Guard" = 
	"Sunblade Protector" = 
	"Sunblade Slayer" = 
	"Sunblade Vindicator" = 
	"Sunseeker Astromage" = 
	"Sunseeker Botanist" = 
	"Sunseeker Harvester" = 
	"Syphoner" = 
	"Terestian Illhoof" = 
	"The Crone" = 
	"The Prophet Skeram" = 
	"Thorngrin the Tender" = 
	"Thuzadin Shadowcaster" = 
	"Time-Lost Shadowmage" = 
	"Twilight Darkcaster" = 
	"Twilight Emissary" = 
	"Unchained Doombringer" = 
	"Underbat" = 
	"Unliving Atal'ai" = 
	"Vashj'ir Honor Guard" = 
	"Vem" = 
	"Viscidus" = 
	"Warlord Kalithresh" = 
	"Warp Splinter" = 
	"Weapon Technician" = 
	"Wrath Hammer Construct" = 
	"Zul'jin" = 
	"Zulian Tiger" = 
	]]--