--[[
************************************************************************
enUS.lua
enUS localization strings for Ackis Recipe List
************************************************************************
File date: @file-date-iso@ 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: @project-version@
************************************************************************
Translation credits: http://www.wowace.com/addons/arl/localization/translators/

Please make sure you update the ToC file with any translations.

Please update http://www.wowace.com/addons/arl/localization/enUS/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.
************************************************************************
Please see http://www.wowace.com/addons/arl/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--


local is_silent = true
--@debug@
is_silent = false
--@end-debug@

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "enUS", true, is_silent)

if not L then return end

--@localization(locale="enUS", format="lua_additive_table", handle-unlocalized="english", escape-non-ascii=false, same-key-is-true=true)@