--[[
****************************************************************************************

ARLLocals-zhCN.lua

zhCN localization strings for Ackis Recipe List

File date: @file-date-iso@ 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: @project-version@

Original translated by: iCat (msn: lucifer_icat@hotmail.com)
Currently maintained by: Kurax, 冰焱妩魅 @ CWDG, ananhaid

Please make sure you update the ToC file with any translations.

The enUS file is auto-generated from the data miner.  If you need to make changes,
please update the data miner file otherwise they will be overwritten.

****************************************************************************************
]]--

--[[
Locale schema
	* single and double words are just fine, anything longer should have a tag
	* tag name rules:
		* tags should be ALL_CAPITAL_LETTERS with words separated with _'s
		* descriptions are typically used in tooltips and header in sections
		* short descriptions will end in _DESC
		* long descriptions will end in _LONG
	* don't include the object being described in the name (no _TOGGLE or _TT) since it
	  can be used several times to describe different objects (in theory)
	* group related elements together, either by their location in the GUI/config,
	  or by purpose (Weapon categories, etc)
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "zhCN", false);

if not L then return end

-- General strings
L["Filters"] 				= "过滤"
L["All"] 					= "全部"
L["None"] 					= "无"
L["Ok"]						= "确定"

-- Command line options
L["Profile"]				= "配置文件"
L["Filter"]					= "过滤"

-- Config Options
L["About"] 					= "关于"
L["Main Options"]			= "主选项"
L["General Settings"]		= "主要设置"
L["Display Settings"]		= "显示设置"
L["Sorting Settings"]		= "种类设置"
L["Profile Options"]		= "配置文件选项"
L["ARL Documentation"]		= "ARL 文档"

-- Config UI Elements and their associated descriptions
L["MAIN_OPTIONS_DESC"]		= "主配置选项"
L["Scan"]					= "扫描"
L["SCAN_RECIPES_DESC"]		= "扫描并打开缺失的商业技能配方。按 Shift 生成文本导出。"
L["Text Dump"]				= "文本导出"
L["TEXT_DUMP_DESC"]			= "显示所有的食谱并以逗号形式分隔，你可以发送给其他的人。"
L["View Exclusion List"]	= "检视排除列表"
L["Scan Button Position"]	= "扫描按钮位置"
L["SCANBUTTONPOSITION_DESC"] = "你可以自定义扫描按钮在商业技能框架上的位置。"
L["VIEW_EXCLUSION_LIST_DESC"] = "显示一个列表，包含所有被排除的配方列表。"
L["DISPLAY_SETTINGS_DESC"]	= "你可以自定义图形界面。"
L["SORTING_SETTINGS_DESC"]	= "你可以自定义以何种方式显示配方种类。"
L["ARL_DOC_DESC"]			= "Ackis Recipe List 文档"

-- UI Documentation
L["Using Filters"]			= "使用过滤"
L["USING_FILTERS_DESC"]		= "开启/关闭过滤。有两种过滤方式：一为阻止显示所有配方，另一为阻止显示特定的类型。\n第一种过滤方式符合匹配的配方（如：绑定）。如果你切换 ARL 不显示拾取绑定配方，过滤中将不会显示拾取绑定配方。第二种过滤方式为处理获取信息。如果一个配方为某怪掉落或者从商人购买，你切换为不显示商人售卖配方，这个配方仍然会显示但是售卖商人信息会被隐藏。原因是还会有其他办法获取这个配方（怪物掉落），所以仍然会在过滤中显示。"
L["Reporting Bugs"]			= "Bug 报告"
L["REPORTING_BUGS_DESC"]	= "当你要报告个错误（Bug）时，请确认做到以下几点：\n1) 下载最新版本，从 http://www.wowace.com/projects/arl/files/可以找到。\n2) 确认这个 Bug 从未被提出。可以在 http://www.wowace.com/projects/arl/tickets/ 查看到。\n2a) 屏蔽相同类型插件如 Skillet 或 ATSW。\n3) 如果您的问题没有列出，你使用的是最新版本验证您的插件设置。检查过滤，个人喜好等等。\n4) 你发现了一个别人没有报告过的 Bug，在 http://www.wowace.com/projects/arl/tickets/ 新建一个 Ticket 并提交问题。确认在 Ticket 内要包含你好搜到的错误信息（只需错误信息，并不需要你使用的插件列表），配方/你的专业技能，和其他你认为有用的信息。"

-- Config UI Elements and their associated descriptions
L["Include Filtered"]		= "包含过滤"
L["FILTERCOUNT_DESC"]		= "在所有配方中包含已被过滤配方。"
L["Include Excluded"]		= "包含排除"
L["EXCLUDECOUNT_DESC"]		= "在所有配方中包含已被排除配方。"
L["Close GUI"]				= "与商业技能信息界面同时关闭"
L["CLOSEGUI_DESC"]			= "当商业技能信息窗口被关闭时 ARL 窗口同时关闭。"
L["Display Exclusions"]		= "显示排除"
L["DISPLAY_EXCLUSION_DESC"]	= "在列表中显示已被排除的配方。"
L["Reset Window"]			= "重置窗口"
L["RESET_WINDOW_DESC"]		= "重置 ARL 图形界面到默认位置。"
L["UI Scale"]				= "界面缩放"
L["UI_SCALE_DESC"]			= "更改界面缩放。从.5到1.5（1为默认值）"
L["Tooltip Scale"]			= "提示缩放"
L["TOOLTIP_SCALE_DESC"]		= "更改 ARL 提示缩放。从.5到1.5（.9为默认值）"
L["Sorting"]				= "种类"
L["Sort"]					= "种类"
L["Display"]				= "显示"
L["SORTING_DESC"]			= "更改配方的种类显示方式。"
L["Version"]				= "版本："
L["Right"]					= "右侧"
L["Left"]					= "左侧"
L["Name"]					= "名称"
L["Skill"]					= "技能"
L["Location"]				= "位置"
L["Acquisition"]			= "获取"

-- Filter Config Options
L["Filtering Options"]		= "过滤选项"
L["General"]				= "一般"
L["Obtain"]					= "获取"
L["Binding"]				= "绑定"
L["Item"]					= "物品"
L["Armor"]					= "护甲"
L["Weapon"]					= "武器"
L["Player Type"]			= "玩家职业"
L["Reputation"]				= "声望"
L["Old World"]				= "经典旧世"
L["Burning Crusade"]		= "燃烧的远征"
L["Wrath of the Lich King"]	= "巫妖王之怒"

-- Filter Configuration Descriptions
L["FILTERING_OPTIONS_DESC"]					= "你可以自定义要过滤哪些配方。"
L["General Filtering Options"]				= "一般过滤选项"
L["FILTERING_GENERAL_DESC"]					= "配置一般的过滤类型。"
L["Obtain Filtering Options"]				= "获取过滤选项"
L["FILTERING_OBTAIN_DESC"]					= "配置扫描中包含获得的配方。"
L["Binding Filtering Options"]				= "绑定过滤选项"
L["FILTERING_BINDING_DESC"]					= "配置扫描中包含绑定类型。"
L["Item Filtering Options"]					= "物品过滤选项"
L["FILTERING_ITEM_DESC"]					= "配置扫描中包含物品类型。"
L["Armor Filtering Options"]				= "护甲过滤选项"
L["FILTERING_Armor_DESC"]					= "配置扫描中包含护甲类型。"
L["Weapon Filtering Options"]				= "武器过滤选项"
L["FILTERING_WEAPONS_DESC"]					= "配置武器扫描中包含类型。"
L["Player Type Filtering Options"]			= "玩家职业过滤选项"
L["FILTERING_PLAYERTYPE_DESC"]				= "配置扫描中包含玩家职业限定的物品类型。"
L["Reputation Filtering Options"]			= "声望过滤选项"
L["FILTERING_REP_DESC"]						= "配置扫描中包含声望奖励类型。"
L["Old World Rep. Filtering Options"]		= "经典旧世声望过滤选项"
L["FILTERING_OLDWORLD_DESC"]				= "配置扫描中包含经典旧世声望类型。 "
L["Burning Crusade Rep. Filtering Options"]	= "燃烧的远征声望过滤选项"
L["FILTERING_BC_DESC"]						= "配置扫描中包含燃烧的远征声望奖励类型。"
L["Lich King Rep. Filtering Options"]		= "巫妖王之怒声望过滤选项"
L["FILTERING_WOTLK_DESC"]					= "配置扫描中包含巫妖王之怒声望奖励类型。"

-- General Filter UI Elements and their associated descriptions
L["Faction"] 				= "阵营"
L["FACTION_DESC"]			= "扫描中包含联盟和部落共有的配方。"
L["Classes"] 				= "职业"
L["CLASS_DESC"] 			= "扫描中包含职业限定的配方。"
L["Specialties"] 			= "技能专业"
L["SPECIALTY_DESC"] 			= "扫描中包含所有商业技能专业。"
L["Skill"] 					= "技能"
L["SKILL_DESC"] 			= "扫描中包含所有配方，而不管你当前的技能等级是多少。"
L["Known"] 					= "已知"
L["KNOWN_DESC"]				= "扫描中包含已知配方。"
L["Unknown"] 				= "未知"
L["UNKNOWN_DESC"]			= "扫描中包含未知配方。"

-- Obtain Filter UI Elements and their associated descriptions
L["Instance"] 				= "副本"
L["INSTANCE_DESC"]			= "扫描中包含5人副本配方。"
L["Raid"]					= "团队"
L["RAID_DESC"]				= "扫描中包含团队副本配方。（如：熔火之心， 毒蛇神殿，等等。）"
L["Quest"]					= "任务"
L["QUEST_DESC"]				= "扫描中包含任务奖励配方。"
L["Seasonal"]				= "季节性"
L["SEASONAL_DESC"]			= "扫描中包含季节性配方。"
L["Trainer"]				= "训练师"
L["TRAINER_DESC"]			= "扫描中包含训练师配方。"
L["Vendor"]					= "商人"
L["VENDOR_DESC"]			= "扫描中包含商人配方。"
L["PVP"]					= "PvP"
L["PVP_DESC"]				= "扫描中包含 PvP 配方。"
L["Discovery"]				= "领悟"
L["DISCOVERY_DESC"]			= "扫描中包含领悟配方。"
L["World Drop"]				= "世界掉落"
L["WORLD_DROP_DESC"]		= "扫描中包含世界掉落配方。"
L["Mob Drop"]				= "怪物掉落"
L["MOB_DROP_DESC"]			= "扫描中包含怪物掉落配方。"

-- Binding Filter UI Elements and their associated descriptions
L["BOEFilter"]				= "装备绑定物品"
L["BOE_DESC"]				= "扫描中包含装备绑定物品配方。"
L["BOPFilter"]				= "拾取绑定物品"
L["BOP_DESC"]				= "扫描中包含拾取绑定物品配方。"
L["BOAFilter"]				= "帐号绑定物品"
L["BOA_DESC"]				= "扫描中包含帐号绑定物品配方。"
L["RecipeBOEFilter"]		= "装备绑定配方"
L["RECIPE_BOE_DESC"]		= "扫描中包含装备绑定配方。"
L["RecipeBOPFilter"]		= "拾取绑定配方"
L["RECIPE_BOP_DESC"]		= "扫描中包含拾取绑定配方。"
L["RecipeBOAFilter"]		= "帐号绑定配方"
L["RECIPE_BOA_DESC"]		= "扫描中包含帐号绑定配方。"

-- Item - Armor UI Elements and their associated descriptions
L["Cloth"] 					= "布甲"
L["CLOTH_DESC"] 			= "扫描中包含成品为布甲的配方。"
L["Leather"] 				= "皮甲"
L["LEATHER_DESC"] 			= "扫描中包含成品为皮甲的配方。"
L["Mail"] 					= "锁甲"
L["MAIL_DESC"] 				= "扫描中包含成品为锁甲的配方。"
L["Plate"] 					= "板甲"
L["PLATE_DESC"] 			= "扫描中包含成品为板甲的配方。"
L["Cloak"] 					= "披风"
L["CLOAK_DESC"] 			= "扫描中包含披风配方"
L["Ring"] 					= "戒指"
L["RING_DESC"] 				= "扫描中包含戒指配方"
L["Trinket"] 				= "饰品"
L["TRINKET_DESC"] 			= "扫描中包含饰品配方"
L["Necklace"] 				= "项链"
L["NECKLACE_DESC"] 			= "扫描中包含项链配方"
L["Shield"]					= "盾牌"
L["SHIELD_DESC"]			= "扫描中包含盾牌配方。"

-- Item - Weapon UI Elements and their associated descriptions
L["One Hand"]				= "单手"
L["ONEHAND_DESC"]			= "扫描中包含单手物品配方。"
L["Two Hand"]				= "双手"
L["TWOHAND_DESC"]			= "扫描中包含双手物品配方。"
L["Axe"]					= "斧"
L["AXE_DESC"]				= "扫描中包含成品为斧的配方。"
L["Sword"]					= "剑"
L["SWORD_DESC"]				= "扫描中包含成品为剑的配方。"
L["Mace"]					= "锤"
L["MACE_DESC"]				= "扫描中包含成品为锤的配方。"
L["Polearm"]				= "长柄武器"
L["POLEARM_DESC"]			= "扫描中包含成品为长柄武器的配方。"
L["Dagger"]					= "匕首"
L["DAGGER_DESC"]			= "扫描中包含成品为匕首的配方。"
L["Fist"]					= "拳套"
L["FIST_DESC"]				= "扫描中包含成品为全套的配方。"
L["Staff"]					= "法杖"
L["STAFF_DESC"]				= "扫描中包含成品为法杖的配方。"
L["Wand"]					= "魔杖"
L["WAND_DESC"]				= "扫描中包含成品为魔杖的配方。"
L["Thrown"]					= "投掷武器"
L["THROWN_DESC"]			= "扫描中包含成品为投掷武器的配方。"
L["Bow"]					= "弓"
L["BOW_DESC"]				= "扫描中包含成品为弓的配方。"
L["Crossbow"]				= "弩"
L["CROSSBOW_DESC"]			= "扫描中包含成品为弩的配方。"
L["Ammo"]					= "弹药"
L["AMMO_DESC"]				= "扫描中包含弹药配方。"

-- Player Type Filtering UI Elements and their associated descriptions
L["Melee DPS"]				= "肉搏 DPS"
L["MELEE_DPS_DESC"]			= "扫描中包含成品适用于肉搏 DPS 的配方。"
L["Tanks"]					= "坦克"
L["TANKS_DESC"]				= "扫描中包含成品适用于坦克职业的配方"
L["Caster DPS"]				= "远程 DPS"
L["CASTER_DPS_DESC"]		= "扫描中包含成品适用于远程 DPS 职业的配方"
L["Healers"]				= "治疗"
L["HEALERS_DESC"]			= "扫描中包含成品适用于治疗职业的配方"

-- Reputation Filtering UI Elements and their associated description
L["SPECIFIC_REP_DESC"]		= "包含%s阵营。"

-- ZJUI UI Elements (when different from the above ones) and their associated descriptions
L["FILTER_OPEN"]			= "过滤 >>>"
L["FILTER_OPEN_DESC"]		= "打开过滤选项面板。"
L["FILTER_CLOSE"]			= "<<< 过滤"
L["FILTER_CLOSE_DESC"]		= "关闭过滤选项面板。"
L["EXPANDALL"]				= "+ 全部"
L["EXPANDALL_DESC"]			= "在下面展开全部配方列表。"
L["CONTRACTALL"]			= "- 全部"
L["CONTRACTALL_DESC"]		= "在下面最小化所有配方列表。"
L["Search"]					= "查找"
L["SEARCH_DESC"]			= "从左侧文字过滤查找配方。"
L["SEARCH_BOX_DESC"]		= "输入文字查找"
L["CLEAR_DESC"]				= "清除查找文本框。"
L["Close"]					= "退出"
L["CLOSE_DESC"]				= "关闭 Ackis Recipe List 窗口。"
L["Reset"]					= "重置"
L["RESET_DESC"]				= "重置所有过滤为默认值。"
L["Apply"]					= "应用"
L["APPLY_DESC"]				= "应用以上所选过滤到配方列表。"
L["ARMOR_ALL_DESC"]			= "扫描中包含“所有”成品为护甲的配方。"
L["ARMOR_NONE_DESC"]		= "扫描中“不”包含成品为护甲的配方。"
L["WEAPON_ALL_DESC"]		= "扫描中包含“所有”成品为武器的配方。"
L["WEAPON_NONE_DESC"]		= "扫描中“不”包含成品为护甲的配方。"
L["NOT_YET_SCANNED"]		= "还未扫描！"

-- Common Tool tip Strings (where different from above)
L["CTRL_CLICK"]			= "Ctrl-左键添加这个配方链接到聊天。"
L["ALT_CLICK"]			= "Alt-左键添加/删除这个配方到你的忽略列表。"
L["SHIFT_CLICK"]		= "Shift-单击添加这个物品制造配方到聊天。"
L["Obtained From"]		= "获取自"
L["RECIPE_EXCLUDED"]	= "配方在排除列表"
L["Required Skill"]		= "所需技能"

-- Popup Strings
L["NOTSCANNED"]		= "您尚未扫描这个专业。请打开这个专业，然后扫描技能。"
L["ALL_FILTERED"]	= "虽然你已经扫描过这个专业，你所过滤的阻止显示任何配方，请重新设置过滤后再试一次。"
L["ARL_ALLKNOWN"]	= "(^0^) 你学到了这个专业的所有技能！"
L["ARL_ALLEXCLUDED"] = "虽然你已经扫描过这个专业，你所排除的阻止显示任何配方，请重新设置过滤后再试一次。"
L["NO_DISPLAY"] 	= "没有配方。如果你看到了这个信息请到 http://www.wowace.com/projects/arl/tickets 提交一个 Ticket 说明你是如何选择过滤/如何选择排除，和你的专业以及已知/未知配方数目。"

-- Error/warning Text
L["MissingFromDB"] = "：缺少这个数据。\n请告知插件作者添加这个配方。"
L["UnknownTradeSkill"] = "您已经打开了一个不支持这个插件的商业技能窗口。这个商业技能为：%s。请向插件作者提供这条信息。"
L["OpenTradeSkillWindow"] = "请打开商业技能窗口扫描。"
L["SpellIDCache"] = "Spell ID: %s 不是您的本地缓存。请到 http://wow.curseforge.com/projects/ackis-recipe-list/tickets/ 提交 Ticket 包含这个 Spell ID 和你所扫描的专业。"
L["NoItemLink"] = "这个物品没有一个物品链接或者不是您的本地缓存。"

-- Drop Obtain Info
L["Unknown Zone"] = "未知区域"

-- Special Event information
L["Midsummer Fire Festival"] = "仲夏火焰节"
L["Feast of Winters Veil"] = "冬幕节"
L["Lunar Festival"] = "春节"
L["Darkmoon Faire"] = "暗月马戏团"
L["Seasonal"] = "季节性"

-- Monster/Quest/Trainer/Vendor (auto-generatored) strings:

-- Do not translate anything below this line without talking to Ackis first please.

L["40 Tickets - Schematic: Steam Tonk Controller"] = true
L["A Binding Contract"] = true
L["Aaron Hollman"] = true
L["Aayndia Floralwind"] = true
L["Abigail Shiel"] = true
L["Abomination"] = true
L["Abyssal Flamebringer"] = true
L["Adele Fielder"] = true
L["Adelene Sunlance"] = true
L["Aendel Windspear"] = true
L["Aged Dalaran Wizard"] = true
L["Ainderu Summerleaf"] = true
L["Ainethil"] = true
L["Akham"] = true
L["Alanna Raveneye"] = true
L["Alard Schmied"] = true
L["Alchemist Gribble"] = true
L["Alchemist Mallory"] = true
L["Alchemist Pestlezugg"] = true
L["Aldraan"] = true
L["Alegorn"] = true
L["Aleinia"] = true
L["Alestus"] = true
L["Alexandra Bolero"] = true
L["Alexis Marlowe"] = true
L["Almaador"] = true
L["Altaa"] = true
L["Alurmi"] = true
L["Alys Vol'tyr"] = true
L["Amal'thazad"] = true
L["Amani Dragonhawk"] = true
L["Amani Elder Lynx"] = true
L["Amani'shi Axe Thrower"] = true
L["Amani'shi Beast Tamer"] = true
L["Amani'shi Flame Caster"] = true
L["Amani'shi Guardian"] = true
L["Amani'shi Handler"] = true
L["Amani'shi Protector"] = true
L["Amani'shi Scout"] = true
L["Amani'shi Tribesman"] = true
L["Amani'shi Warbringer"] = true
L["Amani'shi Wind Walker"] = true
L["Amin"] = true
L["Amy Davenport"] = true
L["Anchorite Ensham"] = true
L["Anchorite Fateema"] = true
L["Anchorite Paetheus"] = true
L["Ancient Female Vrykul"] = true
L["Andre Firebeard"] = true
L["Andrew Hilbert"] = true
L["Andrion Darkspinner"] = true
L["Anger Guard"] = true
L["Angerclaw Grizzly"] = true
L["Anguished Dead"] = true
L["Anguished Highborne"] = true
L["Annora"] = true
L["Anub'ar Guardian"] = true
L["Anub'ar Prime Guard"] = true
L["Anub'ar Venomancer"] = true
L["Anvilrage Captain"] = true
L["Anvilrage Enforcer"] = true
L["Anvilrage Marshal"] = true
L["Anvilrage Overseer"] = true
L["Anvilrage Soldier"] = true
L["Apocalypse Guard"] = true
L["Apothecary Antonivich"] = true
L["Apothecary Bressa"] = true
L["Apothecary Helbrim"] = true
L["Apothecary Wormwick"] = true
L["Apprentice Darius"] = true
L["Apprentice's Duties"] = true
L["Arathel Sunforge"] = true
L["Arcane Anomaly"] = true
L["Arcane Protector"] = true
L["Arcanist Sheynathren"] = true
L["Arcatraz Sentinel"] = true
L["Archmage Alvareaux"] = true
L["Aresella"] = true
L["Argent Quartermaster Hasana"] = true
L["Argent Quartermaster Lightspark"] = true
L["Argo Strongstout"] = true
L["Arikara"] = true
L["Arkkoran Oracle"] = true
L["Arnok"] = true
L["Arras"] = true
L["Arred"] = true
L["Arrond"] = true
L["Arthur Henslowe"] = true
L["Arthur Moore"] = true
L["Artificer Daelo"] = true
L["Asarnan"] = true
L["Ashenvale Bear"] = true
L["Ashmane Boar"] = true
L["Ashtongue Warrior"] = true
L["Aska Mistrunner"] = true
L["Atal'ai Deathwalker"] = true
L["Atal'ai Warrior"] = true
L["Atal'ai Witch Doctor"] = true
L["Auchenai Monk"] = true
L["Awilo Lon'gomba"] = true
L["Azure Magus"] = true
L["Azure Raider"] = true
L["Azure Sorceror"] = true
L["Azure Stalker"] = true
L["Azure Warder"] = true
L["Badlands Reagent Run II"] = true
L["Balai Lok'Wein"] = true
L["Bale"] = true
L["Balgaras the Foul"] = true
L["Banalash"] = true
L["Banshee"] = true
L["Barbaric Battlements"] = true
L["Barbecued Buzzard Wings"] = true
L["Barim Spilthoof"] = true
L["Bash'ir Spell-Thief"] = true
L["Basil Frye"] = true
L["Baxter"] = true
L["Beer Basted Boar Ribs"] = true
L["Belil"] = true
L["Bemarrin"] = true
L["Bena Winterhoof"] = true
L["Bengus Deepforge"] = true
L["Betty Quin"] = true
L["Black Broodling"] = true
L["Black Dragonspawn"] = true
L["Blackened Ancient"] = true
L["Blackhand Elite"] = true
L["Blackrock Battlemaster"] = true
L["Blackrock Slayer"] = true
L["Blackrock Soldier"] = true
L["Blackrock Worg"] = true
L["Blacksmith Calypso"] = true
L["Bleeding Hollow Darkcaster"] = true
L["Blighted Proto-Drake"] = true
L["Blisterpaw Hyena"] = true
L["Blixrez Goodstitch"] = true
L["Bliztik"] = true
L["Bloodaxe Raider"] = true
L["Bloodhound"] = true
L["Bloodmaul Dire Wolf"] = true
L["Bloodmaul Geomancer"] = true
L["Bloodsail Raider"] = true
L["Bloodwarder Legionnaire"] = true
L["Bloodwarder Vindicator"] = true
L["Bog Giant"] = true
L["Bombus Finespindle"] = true
L["Bonechewer Backbreaker"] = true
L["Bonechewer Destroyer"] = true
L["Bonechewer Devastator"] = true
L["Booker Kells"] = true
L["Borgosh Corebender"] = true
L["Borgus Steelhand"] = true
L["Borto"] = true
L["Borus Ironbender"] = true
L["Borya"] = true
L["Boulderfist Warrior"] = true
L["Bowen Brisboise"] = true
L["Bradley Towns"] = true
L["Braeg Stoutbeard"] = true
L["Brandig"] = true
L["Brawn"] = true
L["Brek Stonehoof"] = true
L["Brikk Keencraft"] = true
L["Brittle Revenant"] = true
L["Bro'kin"] = true
L["Brock Stoneseeker"] = true
L["Brom Brewbaster"] = true
L["Brom Killian"] = true
L["Bronk"] = true
L["Bronk Guzzlegear"] = true
L["Brumeran"] = true
L["Brumman"] = true
L["Brumn Winterhoof"] = true
L["Burbik Gearspanner"] = true
L["Burko"] = true
L["Burrowing Thundersnout"] = true
L["Buzzek Bracketswing"] = true
L["Byancie"] = true
L["Cabal Acolyte"] = true
L["Cabal Cultist"] = true
L["Cabal Fanatic"] = true
L["Cabal Spellbinder"] = true
L["Camberon"] = true
L["Captain Halyndor"] = true
L["Captured Gnome"] = true
L["Carolai Anise"] = true
L["Caryssia Moonhunter"] = true
L["Cataclysm Hound"] = true
L["Catarina Stanford"] = true
L["Catherine Leland"] = true
L["Cave Yeti"] = true
L["Celie Steelwing"] = true
L["Cenarion Dreamwarden"] = true
L["Centipaar Sandreaver"] = true
L["Charred Ancient"] = true
L["Chaw Stronghide"] = true
L["Chillwind Chimaera"] = true
L["Chillwind Ravager"] = true
L["Christoph Jeffcoat"] = true
L["Cielstrasza"] = true
L["Clarise Gnarltree"] = true
L["Clefthoof Bull"] = true
L["Cleric of Karabor"] = true
L["Cliff Breaker"] = true
L["Clintar Dreamwalker"] = true
L["Cloned Ooze"] = true
L["Cloud Serpent"] = true
L["Cluster Launcher"] = true
L["Clyde Ranthal"] = true
L["Cobalt Broodling"] = true
L["Cobalt Mageweaver"] = true
L["Cobalt Scalebane"] = true
L["Cobalt Serpent"] = true
L["Cobalt Whelp"] = true
L["Cobalt Wyrmkin"] = true
L["Coilfang Champion"] = true
L["Coilfang Hate-Screamer"] = true
L["Coilfang Myrmidon"] = true
L["Coilfang Oracle"] = true
L["Coilfang Serpentguard"] = true
L["Coilfang Shatterer"] = true
L["Coilfang Siren"] = true
L["Coilfang Sorceress"] = true
L["Coilfang Technician"] = true
L["Coilfang Warrior"] = true
L["Coilskar Sea-Caller"] = true
L["Cold Eye Basilisk"] = true
L["Commander Dardosh"] = true
L["Commander Malgor"] = true
L["Commander Mulfort"] = true
L["Constance Brisboise"] = true
L["Cook Ghilm"] = true
L["Cookie One-Eye"] = true
L["Coreiel"] = true
L["Corporal Bluth"] = true
L["Corruption"] = true
L["Costly Menace"] = true
L["Crazed Ancient"] = true
L["Crazed Murkblood Foreman"] = true
L["Crazk Sparks"] = true
L["Crimson Inquisitor"] = true
L["Crimson Sorcerer"] = true
L["Cro Threadstrong"] = true
L["Crocolisk Hunting"] = true
L["Crog Steelspine"] = true
L["Crypt Fiend"] = true
L["Crystal Boughman"] = true
L["Crystalcore Mechanic"] = true
L["Crystalline Keeper"] = true
L["Crystalline Protector"] = true
L["Culinary Crunch"] = true
L["Cult Alchemist"] = true
L["Cultist Shard Watcher"] = true
L["Cyndra Kindwhisper"] = true
L["Daedal"] = true
L["Daga Ramba"] = true
L["Daggle Ironshaper"] = true
L["Dalinna"] = true
L["Dalria"] = true
L["Damned Apothecary"] = true
L["Dan Golthas"] = true
L["Dane Lindgren"] = true
L["Daniel Bartlett"] = true
L["Danielle Zipstitch"] = true
L["Dank Drizzlecut"] = true
L["Dannelor"] = true
L["Danwe"] = true
L["Darianna"] = true
L["Dark Adept"] = true
L["Dark Conclave Shadowmancer"] = true
L["Dark Iron Demolitionist"] = true
L["Dark Iron Dwarf"] = true
L["Dark Iron Saboteur"] = true
L["Dark Iron Slaver"] = true
L["Dark Iron Taskmaster"] = true
L["Dark Iron Tunneler"] = true
L["Dark Iron Watchman"] = true
L["Dark Screecher"] = true
L["Dark Strand Voidcaller"] = true
L["Darkspine Myrmidon"] = true
L["Darkspine Siren"] = true
L["Darkwater Crocolisk"] = true
L["Darmari"] = true
L["Darnall"] = true
L["Daryl Riknussun"] = true
L["Daryl Stack"] = true
L["Dawnblade Marksman"] = true
L["Deadwind Warlock"] = true
L["Deadwood Pathfinder"] = true
L["Deadwood Shaman"] = true
L["Dealer Malij"] = true
L["Deathforge Guardian"] = true
L["Deathforge Imp"] = true
L["Deathforge Smith"] = true
L["Deathforge Tinkerer"] = true
L["Deathlash Scorpid"] = true
L["Decaying Horror"] = true
L["Deek Fizzlebizz"] = true
L["Deep Stinger"] = true
L["Defias Enchanter"] = true
L["Defias Looter"] = true
L["Defias Pirate"] = true
L["Defias Profiteer"] = true
L["Defias Renegade Mage"] = true
L["Defias Squallshaper"] = true
L["Delfrum Flintbeard"] = true
L["Deneb Walker"] = true
L["Derak Nightfall"] = true
L["Derek Odds"] = true
L["Deriz"] = true
L["Deviate Eradication"] = true
L["Deynna"] = true
L["Diemetradon"] = true
L["Dig Rat Stew"] = true
L["Dirge Quikcleave"] = true
L["Dirge's Kickin' Chimaerok Chops"] = true
L["Diseased Black Bear"] = true
L["Disembodied Protector"] = true
L["Disembodied Vindicator"] = true
L["Doba"] = true
L["Doctor Herbert Halsey"] = true
L["Doctor Marsh"] = true
L["Doctor Martin Felben"] = true
L["Dolothos"] = true
L["Don Carlos"] = true
L["Doomfire Destroyer"] = true
L["Doomforge Craftsman"] = true
L["Doomforge Dragoon"] = true
L["Doomforge Engineer"] = true
L["Drac Roughcut"] = true
L["Dragonmaw Wind Reaver"] = true
L["Drakk Stonehand"] = true
L["Drovnar Strongbrew"] = true
L["Drywallow Crocolisk"] = true
L["Drywallow Snapper"] = true
L["Duchess Mynx"] = true
L["Duhng"] = true
L["Dulvi"] = true
L["Dunemaul Brute"] = true
L["Durnholde Lookout"] = true
L["Durnholde Rifleman"] = true
L["Durnholde Sentry"] = true
L["Durnholde Tracking Hound"] = true
L["Dusky Crab Cakes"] = true
L["Dwukk"] = true
L["Easy Strider Living"] = true
L["Eclipsion Archmage"] = true
L["Eclipsion Blood Knight"] = true
L["Eclipsion Bloodwarder"] = true
L["Eclipsion Cavalier"] = true
L["Eclipsion Centurion"] = true
L["Eclipsion Dragonhawk"] = true
L["Eclipsion Soldier"] = true
L["Eclipsion Spellbinder"] = true
L["Edna Mullby"] = true
L["Edrem"] = true
L["Eebee Jinglepocket"] = true
L["Egomis"] = true
L["Eiin"] = true
L["Eldara Dawnrunner"] = true
L["Elder Diemetradon"] = true
L["Elder Gray Bear"] = true
L["Elder Shadowhorn Stag"] = true
L["Elder Shardtooth"] = true
L["Elder Stranglethorn Tiger"] = true
L["Eldrin"] = true
L["Elise Brightletter"] = true
L["Elixir of Pain"] = true
L["Elizabeth Jackson"] = true
L["Elynna"] = true
L["Emil Autumn"] = true
L["Emrul Riknussun"] = true
L["Enchanted Thorium Platemail: Volume I"] = true
L["Enchanted Thorium Platemail: Volume II"] = true
L["Enchanted Thorium Platemail: Volume III"] = true
L["Enchanter Aeldron"] = true
L["Enchanter Nalthanis"] = true
L["Enchanter Salias"] = true
L["Enchantress Metura"] = true
L["Enchantress Volali"] = true
L["Enraged Crusher"] = true
L["Enraged Mammoth"] = true
L["Enslaved Proto-Drake"] = true
L["Eorain Dawnstrike"] = true
L["Eredar Deathbringer"] = true
L["Eriden"] = true
L["Erika Tate"] = true
L["Erilia"] = true
L["Erin Kelly"] = true
L["Ethereal Priest"] = true
L["Ethereal Scavenger"] = true
L["Ethereal Spellbinder"] = true
L["Ethereal Thief"] = true
L["Ethereum Nullifier"] = true
L["Ethereum Smuggler"] = true
L["Eunice Burch"] = true
L["Faldron"] = true
L["Falorn Nightwhisper"] = true
L["Farii"] = true
L["Fazu"] = true
L["Fedryen Swiftspear"] = true
L["Feera"] = true
L["Fel Orc Convert"] = true
L["Fel Rager"] = true
L["Fel Stalker"] = true
L["Felannia"] = true
L["Felguard Annihilator"] = true
L["Felicia Doan"] = true
L["Felika"] = true
L["Felpaw Ravager"] = true
L["Felpaw Wolf"] = true
L["Fera Palerunner"] = true
L["Ferocious Yeti"] = true
L["Feruul"] = true
L["Festive Recipes"] = true
L["Feyden Darkin"] = true
L["Fiery Plate Gauntlets"] = true
L["Fimble Finespindle"] = true
L["Finbus Geargrind"] = true
L["Firebrand Grunt"] = true
L["Firebrand Invoker"] = true
L["Firebrand Legionnaire"] = true
L["Firebrand Pyromancer"] = true
L["Firegut Brute"] = true
L["Firework Launcher"] = true
L["Flash Bomb Recipe"] = true
L["Fledgling Chillwind"] = true
L["Fleshbeast"] = true
L["Foreman Marcrid"] = true
L["Forgotten One"] = true
L["Fradd Swiftgear"] = true
L["Franklin Lloyd"] = true
L["Fremal Doohickey"] = true
L["Frenzied Pterrordax"] = true
L["Frost Wyrm"] = true
L["Frostbrood Spawn"] = true
L["Frostfeather Screecher"] = true
L["Frostfeather Witch"] = true
L["Frostmaul Giant"] = true
L["Furywing"] = true
L["Fyldan"] = true
L["Gagsprocket"] = true
L["Galana"] = true
L["Gambarinka"] = true
L["Gara Skullcrush"] = true
L["Gargantuan Abyssal"] = true
L["Gargoyle"] = true
L["Gaston"] = true
L["Gazlowe"] = true
L["Gearcutter Cogspinner"] = true
L["Gearing Redridge"] = true
L["Geen"] = true
L["Gelanthis"] = true
L["Gelman Stonehand"] = true
L["Geofram Bouldertoe"] = true
L["Georgio Bolero"] = true
L["Ghak Healtouch"] = true
L["Ghermas"] = true
L["Ghok'kah"] = true
L["Ghostly Philanthropist"] = true
L["Ghostly Steward"] = true
L["Ghostpaw Alpha"] = true
L["Ghoul"] = true
L["Giant Infernal"] = true
L["Gidge Spellweaver"] = true
L["Gikkix"] = true
L["Gimble Thistlefuzz"] = true
L["Gina MacGregor"] = true
L["Glasshide Basilisk"] = true
L["Glasshide Gazer"] = true
L["Gloresse"] = true
L["Gloria Femmel"] = true
L["Glutinous Ooze"] = true
L["Glyx Brewright"] = true
L["Gnaz Blunderflame"] = true
L["Godan"] = true
L["Gordunni Back-Breaker"] = true
L["Gordunni Elementalist"] = true
L["Gordunni Head-Splitter"] = true
L["Gordunni Soulreaper"] = true
L["Goretusk"] = true
L["Goretusk Liver Pie"] = true
L["Gorgolon the All-seeing"] = true
L["Gorishi Reaver"] = true
L["Graham Van Talen"] = true
L["Grarnik Goodstitch"] = true
L["Great Goretusk"] = true
L["Great-father Winter"] = true
L["Greater Bogstrok"] = true
L["Greater Fleshbeast"] = true
L["Gremlock Pilsnor"] = true
L["Gretta Finespindle"] = true
L["Gretta Ganter"] = true
L["Grikka"] = true
L["Grimtak"] = true
L["Grimtotem Geomancer"] = true
L["Grondal Moonbreeze"] = true
L["Groum Stonebeard"] = true
L["Grumnus Steelshaper"] = true
L["Grutah"] = true
L["Guillaume Sorouy"] = true
L["Gundrak Savage"] = true
L["Haalrun"] = true
L["Haferet"] = true
L["Hagrus"] = true
L["Hahrana Ironhide"] = true
L["Hama"] = true
L["Hamanar"] = true
L["Hammered Patron"] = true
L["Hammon Karwn"] = true
L["Harlown Darkweave"] = true
L["Harn Longcast"] = true
L["Hatefury Shadowstalker"] = true
L["Haughty Modiste"] = true
L["Hch'uu"] = true
L["Helboar"] = true
L["Heldan Galesong"] = true
L["Helenia Olden"] = true
L["Hgarth"] = true
L["High Enchanter Bardolan"] = true
L["Highland Raptor"] = true
L["Highlord Darion Mograine"] = true
L["Hillsbrad Tailor"] = true
L["Himmik"] = true
L["Homunculus"] = true
L["Horns of Frenzy"] = true
L["Hulking Mountain Lion"] = true
L["Humphry"] = true
L["Hurnak Grimmord"] = true
L["Ice Thistle Matriarch"] = true
L["Ice Thistle Patriarch"] = true
L["Ice Thistle Yeti"] = true
L["Icemane Yeti"] = true
L["Ildine Sorrowspear"] = true
L["Illidari Defiler"] = true
L["Illidari Heartseeker"] = true
L["Illidari Shocktrooper"] = true
L["Illidari Watcher"] = true
L["Imperial Plate Belt"] = true
L["Imperial Plate Boots"] = true
L["Imperial Plate Bracer"] = true
L["Imperial Plate Chest"] = true
L["Imperial Plate Helm"] = true
L["Imperial Plate Leggings"] = true
L["Imperial Plate Shoulders"] = true
L["Incandescent Fel Spark"] = true
L["Incendosaur"] = true
L["Indormi"] = true
L["Innkeeper Biribi"] = true
L["Innkeeper Fizzgrimble"] = true
L["Innkeeper Grilka"] = true
L["Insidion"] = true
L["Iron Rune-Shaper"] = true
L["Ironbark Protector"] = true
L["Ironus Coldsteel"] = true
L["Ironwool Mammoth"] = true
L["Jabbey"] = true
L["Jack Trapper"] = true
L["Jadefire Felsworn"] = true
L["Jadefire Rogue"] = true
L["Jalane Ayrole"] = true
L["James Van Brunt"] = true
L["Jamesina Watterly"] = true
L["Jandia"] = true
L["Janet Hommers"] = true
L["Jannos Ironwill"] = true
L["Jase Farlane"] = true
L["Jaxin Chong"] = true
L["Jazdalaad"] = true
L["Jazzrik"] = true
L["Jeeda"] = true
L["Jemma Quikswitch"] = true
L["Jenna Lemkenilli"] = true
L["Jennabink Powerseam"] = true
L["Jessara Cordell"] = true
L["Jhag"] = true
L["Jim Saltit"] = true
L["Jinky Twizzlefixxit"] = true
L["Jo'mah"] = true
L["Johan Barnes"] = true
L["Johan Focht"] = true
L["Jormund Stonebrow"] = true
L["Josef Gregorian"] = true
L["Joseph Moore"] = true
L["Josephine Lister"] = true
L["Josric Fame"] = true
L["Joys of Omosh"] = true
L["Jubie Gadgetspring"] = true
L["Jun'ha"] = true
L["Juno Dufrain"] = true
L["Justin Oshenko"] = true
L["Jutak"] = true
L["K. Lee Smallfry"] = true
L["Kalaen"] = true
L["Kalinda"] = true
L["Kalldan Felmoon"] = true
L["Kamari"] = true
L["Kanaria"] = true
L["Kania"] = true
L["Karaaz"] = true
L["Karn Stonehoof"] = true
L["Karolek"] = true
L["Katherine Lee"] = true
L["Kayaart"] = true
L["Keelen Sheets"] = true
L["Keena"] = true
L["Kelgruk Bloodaxe"] = true
L["Kelsey Yance"] = true
L["Kendor Kabonka"] = true
L["Khara Deepwater"] = true
L["Khole Jinglepocket"] = true
L["Kiknikle"] = true
L["Kil'hala"] = true
L["Killian Sanatha"] = true
L["Kilxx"] = true
L["Kireena"] = true
L["Kithas"] = true
L["Kitta Firewind"] = true
L["Klaven's Tower"] = true
L["Knaz Blunderflame"] = true
L["Knight Dameron"] = true
L["Kodo Hide Bag"] = true
L["Kor'geld"] = true
L["Koren"] = true
L["Kradu Grimblade"] = true
L["Kray"] = true
L["Krek Cragcrush"] = true
L["Kriggon Talsone"] = true
L["Kristen Smythe"] = true
L["Krugosh"] = true
L["Krulmoo Fullmoon"] = true
L["Krunn"] = true
L["Kudrii"] = true
L["Kulwia"] = true
L["Kurdram Stonehammer"] = true
L["Kurzen Commando"] = true
L["Kylanna"] = true
L["Kylanna Windwhisper"] = true
L["Kylene"] = true
L["Kzixx"] = true
L["Lady Alistra"] = true
L["Laird"] = true
L["Lalina Summermoon"] = true
L["Lalla Brightweave"] = true
L["Landraelanis"] = true
L["Lanolis Dewdrop"] = true
L["Lavinia Crowe"] = true
L["Lawrence Schneider"] = true
L["Lebowski"] = true
L["Leeli Longhaggle"] = true
L["Legashi Rogue"] = true
L["Leo Sarn"] = true
L["Leonard Porter"] = true
L["Lesser Infernal"] = true
L["Librarian Erickson"] = true
L["Lieutenant General Andorov"] = true
L["Lieutenant Lewis"] = true
L["Lieutenant Mancuso"] = true
L["Lightsworn Vindicator"] = true
L["Lillehoff"] = true
L["Lilliam Sparkspindle"] = true
L["Lilly"] = true
L["Lilyssia Nightbreeze"] = true
L["Lindea Rabonne"] = true
L["Linna Bruder"] = true
L["Linzy Blackbolt"] = true
L["Liquid Stone"] = true
L["Lizbeth Cromwell"] = true
L["Logistics Officer Brighton"] = true
L["Logistics Officer Silverstone"] = true
L["Logistics Officer Ulrike"] = true
L["Lokhtos Darkbargainer"] = true
L["Loolruna"] = true
L["Lord Thorval"] = true
L["Lorelae Wintersong"] = true
L["Lorokeem"] = true
L["Lucan Cordell"] = true
L["Lucc"] = true
L["Lyna"] = true
L["Lynalis"] = true
L["Mack Diver"] = true
L["Madame Ruby"] = true
L["Magar"] = true
L["Mage Slayer"] = true
L["Mageslayer"] = true
L["Magical Horror"] = true
L["Magistrix Eredania"] = true
L["Magnus Frostwake"] = true
L["Mahani"] = true
L["Mahu"] = true
L["Mak"] = true
L["Makaru"] = true
L["Malcomb Wynn"] = true
L["Mallen Swain"] = true
L["Malygen"] = true
L["Mana Warp"] = true
L["Margaux Parchley"] = true
L["Mari Stonehand"] = true
L["Maria Lumere"] = true
L["Martine Tramblay"] = true
L["Mary Edras"] = true
L["Master Chef Mouldier"] = true
L["Master Craftsman Omarion"] = true
L["Master of the Wild Leather"] = true
L["Mathar G'ochar"] = true
L["Matt Johnson"] = true
L["Mavralyn"] = true
L["Mazk Snipeshot"] = true
L["Me'lynn"] = true
L["Meilosh"] = true
L["Melaris"] = true
L["Miall"] = true
L["Miao'zan"] = true
L["Micha Yance"] = true
L["Michael Schwan"] = true
L["Michelle Belle"] = true
L["Mildred Fletcher"] = true
L["Milla Fairancora"] = true
L["Millie Gregorian"] = true
L["Mindri Dinkles"] = true
L["Mire Lord"] = true
L["Mirvedon"] = true
L["Misensi"] = true
L["Mishta"] = true
L["Mission: Possible But Not Probable"] = true
L["Mixie Farshot"] = true
L["Mo'arg Incinerator"] = true
L["Mo'arg Weaponsmith"] = true
L["Modoru"] = true
L["Mok'Nathal Treats"] = true
L["Montarr"] = true
L["Moonglow Vest"] = true
L["Moonrage Tailor"] = true
L["Moordo"] = true
L["Morgan Day"] = true
L["Mossflayer Shadowhunter"] = true
L["Mot Dawnstrider"] = true
L["Muaat"] = true
L["Muculent Ooze"] = true
L["Mudduk"] = true
L["Muheru the Weaver"] = true
L["Mukdrak"] = true
L["Mumman"] = true
L["Murk Spitter"] = true
L["Murk Worm"] = true
L["Murkblood Putrifier"] = true
L["Murkblood Raider"] = true
L["Mutant Horror"] = true
L["Muuran"] = true
L["Mycah"] = true
L["Mythrin'dir"] = true
L["Naal Mistrunner"] = true
L["Nadyia Maneweaver"] = true
L["Nahogg"] = true
L["Naka"] = true
L["Nakodu"] = true
L["Namdo Bizzfizzle"] = true
L["Nandar Branson"] = true
L["Nardstrum Copperpinch"] = true
L["Narj Deepslice"] = true
L["Narv Hidecrafter"] = true
L["Nascent Val'kyr"] = true
L["Nasmara Moonsong"] = true
L["Nata Dawnstrider"] = true
L["Neal Allen"] = true
L["Neferatti"] = true
L["Neii"] = true
L["Nerrist"] = true
L["Nessa Shadowsong"] = true
L["Nethergarde Engineer"] = true
L["Nethervine Inciter"] = true
L["Nexus Stalker"] = true
L["Nightmare Scalebane"] = true
L["Nimar the Slayer"] = true
L["Nissa Firestone"] = true
L["Nixx Sprocketspring"] = true
L["Nogg"] = true
L["Nula the Butcher"] = true
L["Nurse Neela"] = true
L["Nus"] = true
L["Oblivion Mage"] = true
L["Obsidia"] = true
L["Ockil"] = true
L["Ogg'marr"] = true
L["Oglethorpe Obnoticus"] = true
L["Okothos Ironrager"] = true
L["Okuno"] = true
L["On Iron Pauldrons"] = true
L["Onslaught Bloodhound"] = true
L["Onslaught Mason"] = true
L["Ontuvo"] = true
L["Ormer's Revenge"] = true
L["Orn Tenderhoof"] = true
L["Otho Moji'ko"] = true
L["Outfitter Eric"] = true
L["Padaar"] = true
L["Painbringer"] = true
L["Pand Stonebinder"] = true
L["Paulsta'ats"] = true
L["Penney Copperpinch"] = true
L["Peter Galen"] = true
L["Phantom Attendant"] = true
L["Phantom Guardsman"] = true
L["Phantom Guest"] = true
L["Phantom Stagehand"] = true
L["Phantom Valet"] = true
L["Phea"] = true
L["Phoenix-Hawk"] = true
L["Phoenix-Hawk Hatchling"] = true
L["Pikkle"] = true
L["Plains Mammoth"] = true
L["Portal Guardian"] = true
L["Portal Keeper"] = true
L["Poshken Hardbinder"] = true
L["Pratt McGrubben"] = true
L["Priestess of Torment"] = true
L["Primal Ooze"] = true
L["Primordial Behemoth"] = true
L["Primordial Drake"] = true
L["Professor Pallin"] = true
L["Prospector Nachlan"] = true
L["Provisioner Lorkran"] = true
L["Provisioner Nasela"] = true
L["Pterrordax"] = true
L["Pyall Silentstride"] = true
L["Pyrewood Tailor"] = true
L["Qia"] = true
L["Quarelestra"] = true
L["Quartermaster Davian Vaclav"] = true
L["Quartermaster Endarin"] = true
L["Quartermaster Enuril"] = true
L["Quartermaster Jaffrey Noreliqe"] = true
L["Quartermaster Miranda Breechlock"] = true
L["Quartermaster Urgronn"] = true
L["Quelis"] = true
L["Rabid Shardtooth"] = true
L["Rabid Warhound"] = true
L["Rage Talon Dragon Guard"] = true
L["Raging Skeleton"] = true
L["Randal Worth"] = true
L["Ranik"] = true
L["Rann Flamespinner"] = true
L["Rathis Tomber"] = true
L["Ravaged Cadaver"] = true
L["Rawrk"] = true
L["Razia"] = true
L["Recipe of the Kaldorei"] = true
L["Redridge Goulash"] = true
L["Redstone Basilisk"] = true
L["Refik"] = true
L["Rhiannon Davis"] = true
L["Rhonsus"] = true
L["Ribbly's Crony"] = true
L["Rift Keeper"] = true
L["Rift Lord"] = true
L["Rikqiz"] = true
L["Rin'wosho the Trader"] = true
L["Risen Bonewarder"] = true
L["Risen Construct"] = true
L["Risen Drakkari Death Knight"] = true
L["Rivendark"] = true
L["Rizz Loosebolt"] = true
L["Rogue Ice Thistle"] = true
L["Rogvar"] = true
L["Rohok"] = true
L["Rollick MacKreel"] = true
L["Ronald Burch"] = true
L["Rosina Rivet"] = true
L["Rotgath Stonebeard"] = true
L["Rotting Behemoth"] = true
L["Roxxik"] = true
L["Rungor"] = true
L["Ruppo Zipcoil"] = true
L["Sable Jaguar"] = true
L["Saenorion"] = true
L["Sairuk"] = true
L["Saltstone Basilisk"] = true
L["Sandfury Blood Drinker"] = true
L["Sandfury Shadowcaster"] = true
L["Sarah Tanner"] = true
L["Saru Steelfury"] = true
L["Sassa Weldwell"] = true
L["Sathein"] = true
L["Savage Worg"] = true
L["Sawtooth Crocolisk"] = true
L["Scargil"] = true
L["Scarlet Adept"] = true
L["Scarlet Archmage"] = true
L["Scarlet Cavalier"] = true
L["Scarlet Centurion"] = true
L["Scarlet Gallant"] = true
L["Scarlet Monk"] = true
L["Scarlet Myrmidon"] = true
L["Scarlet Protector"] = true
L["Scarlet Smith"] = true
L["Scarlet Spellbinder"] = true
L["Scarlet Warder"] = true
L["Scholomance Adept"] = true
L["Scholomance Necromancer"] = true
L["Scorched Basilisk"] = true
L["Scorpid Hunter"] = true
L["Scorpid Tail Lasher"] = true
L["Se'Jib"] = true
L["Seasoned Wolf Kabobs"] = true
L["Sebastian Crane"] = true
L["Sedana"] = true
L["Seer Janidi"] = true
L["Seersa Copperpinch"] = true
L["Sellandus"] = true
L["Selling Fish"] = true
L["Sempstress Ambershine"] = true
L["Serge Hinott"] = true
L["Serpentshrine Sporebat"] = true
L["Sethekk Initiate"] = true
L["Sethekk Prophet"] = true
L["Sethekk Ravenguard"] = true
L["Sewa Mistrunner"] = true
L["Shaani"] = true
L["Shadi Mistrunner"] = true
L["Shadow Council Warlock"] = true
L["Shadow Pillager"] = true
L["Shadowforge Peasant"] = true
L["Shadowmage"] = true
L["Shadowmaw Panther"] = true
L["Shadowmoon Reaver"] = true
L["Shadowsword Assassin"] = true
L["Shadowsword Guardian"] = true
L["Shadowsword Vanquisher"] = true
L["Shadowsworn Drakonid"] = true
L["Shadowsworn Thug"] = true
L["Shadowy Necromancer"] = true
L["Shaina Fuller"] = true
L["Shankys"] = true
L["Shardtooth Bear"] = true
L["Shardtooth Mauler"] = true
L["Sharing the Knowledge"] = true
L["Shattered Hand Centurion"] = true
L["Shattered Hand Champion"] = true
L["Shattertusk Bull"] = true
L["Shattertusk Mammoth"] = true
L["Shayis Steelfury"] = true
L["Sheendra Tallgrass"] = true
L["Shelene Rhobart"] = true
L["Shen'dralar Provisioner"] = true
L["Sheri Zipstitch"] = true
L["Shrike Bat"] = true
L["Sid Limbardi"] = true
L["Silvermane Stalker"] = true
L["Simon Tanner"] = true
L["Simon Unit"] = true
L["Singed Basilisk"] = true
L["Sister of Torment"] = true
L["Skeletal Flayer"] = true
L["Skeletal Runesmith"] = true
L["Skeletal Usher"] = true
L["Skettis Soulcaller"] = true
L["Skreah"] = true
L["Skullsplitter Mystic"] = true
L["Slagg"] = true
L["Slave Worker"] = true
L["Slavering Ghoul"] = true
L["Smelt On, Smelt Off"] = true
L["Smith Argus"] = true
L["Smooth as Butter"] = true
L["Smudge Thunderwood"] = true
L["Snakestone of the Shadow Huntress"] = true
L["Snang"] = true
L["Snarl"] = true
L["Sock Brightbolt"] = true
L["Son of Arkkoroc"] = true
L["Soothing Turtle Bisque"] = true
L["Sorcerous Shade"] = true
L["Southsea Pirate"] = true
L["Sovik"] = true
L["Sparkleshell Snapper"] = true
L["Spawn of Hakkar"] = true
L["Spectral Charger"] = true
L["Spectral Performer"] = true
L["Spectral Researcher"] = true
L["Spectral Servant"] = true
L["Spectral Stable Hand"] = true
L["Spectral Stallion"] = true
L["Spell Eater"] = true
L["Spell Shade"] = true
L["Spellmaw"] = true
L["Spirestone Warlord"] = true
L["Splinterbone Centurion"] = true
L["Springspindle Fizzlegear"] = true
L["Sprite Jumpsprocket"] = true
L["Starving Blisterpaw"] = true
L["Stephen Ryback"] = true
L["Stoic Mammoth"] = true
L["Stone Guard Mukar"] = true
L["Stonevault Oracle"] = true
L["Stonevault Pillager"] = true
L["Storm Fury"] = true
L["Stormforged Ambusher"] = true
L["Stormforged Artificer"] = true
L["Stormforged Champion"] = true
L["Stormforged Giant"] = true
L["Stormforged Infiltrator"] = true
L["Stranglethorn Tigress"] = true
L["Strashaz Myrmidon"] = true
L["Strashaz Warrior"] = true
L["Stuart Fleming"] = true
L["Subterranean Diemetradon"] = true
L["Sumi"] = true
L["Sunblade Arch Mage"] = true
L["Sunblade Blood Knight"] = true
L["Sunblade Cabalist"] = true
L["Sunblade Dawn Priest"] = true
L["Sunblade Dusk Priest"] = true
L["Sunblade Mage Guard"] = true
L["Sunblade Protector"] = true
L["Sunblade Slayer"] = true
L["Sunblade Vindicator"] = true
L["Sunfury Arcanist"] = true
L["Sunfury Arch Mage"] = true
L["Sunfury Archer"] = true
L["Sunfury Bloodwarder"] = true
L["Sunfury Bowman"] = true
L["Sunfury Researcher"] = true
L["Sunscale Scytheclaw"] = true
L["Sunseeker Astromage"] = true
L["Sunseeker Botanist"] = true
L["Sunseeker Harvester"] = true
L["Super-Seller 680"] = true
L["Supply Officer Mills"] = true
L["Supplying the Front"] = true
L["Swampwalker"] = true
L["Swampwalker Elder"] = true
L["Sweet Serenity"] = true
L["Sylann"] = true
L["Sylvanna Forestmoon"] = true
L["Syndicate Assassin"] = true
L["Syndicate Mercenary"] = true
L["Syndicate Pathstalker"] = true
L["Syndicate Spy"] = true
L["Syphoner"] = true
L["Taladan"] = true
L["Tally Berryfizz"] = true
L["Talmar"] = true
L["Tamar"] = true
L["Tanaika"] = true
L["Tanak"] = true
L["Tangled Horror"] = true
L["Tansy Puddlefizz"] = true
L["Tar Lurker"] = true
L["Tarban Hearthgrain"] = true
L["Tari'qa"] = true
L["Tarn"] = true
L["Tatiana"] = true
L["Teg Dawnstrider"] = true
L["Tel'Athir"] = true
L["Telonis"] = true
L["Tempered War Golem"] = true
L["Tepa"] = true
L["Terrormaster"] = true
L["Thaddeus Webb"] = true
L["Thamner Pol"] = true
L["Tharynn Bouden"] = true
L["Thaurissan Firewalker"] = true
L["The Art of the Imbue"] = true
L["The Demon Forge"] = true
L["The Great Moongraze Hunt"] = true
L["The Great Silver Deceiver"] = true
L["The Journey Has Just Begun"] = true
L["The Old Ways"] = true
L["The Origins of Smithing"] = true
L["The Rescue"] = true
L["The Undermarket"] = true
L["The Zapthrottle Mote Extractor!"] = true
L["Thelsamar Blood Sausages"] = true
L["Theramore Infiltrator"] = true
L["Theramore Marine"] = true
L["Theramore Preserver"] = true
L["Therum Deepforge"] = true
L["Thistleshrub Dew Collector"] = true
L["Thomas Kolichio"] = true
L["Thomas Yance"] = true
L["Thonys Pillarstone"] = true
L["Thorkaf Dragoneye"] = true
L["Thoth"] = true
L["Thrag Stonehoof"] = true
L["Thrashtail Basilisk"] = true
L["Thund"] = true
L["Thuzadin Shadowcaster"] = true
L["Tiffany Cartier"] = true
L["Tilli Thistlefuzz"] = true
L["Timber Worg Alpha"] = true
L["Time-Lost Shadowmage"] = true
L["Timothy Worthington"] = true
L["Tink Brightbolt"] = true
L["Tinkerwiz"] = true
L["Tinkmaster Overspark"] = true
L["Tisha Longbridge"] = true
L["Tognus Flintfire"] = true
L["Tomas"] = true
L["Torloth the Magnificent"] = true
L["Torn Fin Coastrunner"] = true
L["Torn Fin Muckdweller"] = true
L["Torn Fin Oracle"] = true
L["Torn Fin Tidehunter"] = true
L["Trampled Under Foot"] = true
L["Traugh"] = true
L["Trianna"] = true
L["Trixie Quikswitch"] = true
L["Truk Wildbeard"] = true
L["Tunkk"] = true
L["Twilight Dark Shaman"] = true
L["Twilight Emissary"] = true
L["Twilight Fire Guard"] = true
L["Twilight Geomancer"] = true
L["Ug'thok"] = true
L["Ulthaan"] = true
L["Ulthir"] = true
L["Un'Goro Gorilla"] = true
L["Un'Goro Stomper"] = true
L["Una"] = true
L["Unchained Doombringer"] = true
L["Underbat"] = true
L["Unleashed Hellion"] = true
L["Unliving Atal'ai"] = true
L["Uriku"] = true
L["Ursius"] = true
L["Uthok"] = true
L["Uthrar Threx"] = true
L["Vaean"] = true
L["Valdaron"] = true
L["Vance Undergloom"] = true
L["Vanessa Sellers"] = true
L["Vargus"] = true
L["Vazario Linkgrease"] = true
L["Vekh'nir Dreadhawk"] = true
L["Venom Mist Lurker"] = true
L["Venture Co. Excavator"] = true
L["Venture Co. Strip Miner"] = true
L["Veteran Crusader Aliocha Segard"] = true
L["Vhan"] = true
L["Victor Ward"] = true
L["Viggz Shinesparked"] = true
L["Vilebranch Hideskinner"] = true
L["Vilebranch Raiding Wolf"] = true
L["Vilebranch Soothsayer"] = true
L["Vir'aani Arcanist"] = true
L["Vira Younghoof"] = true
L["Vivianna"] = true
L["Vix Chromeblaster"] = true
L["Vizzklick"] = true
L["Vodesiin"] = true
L["Voidshrieker"] = true
L["Voidspawn"] = true
L["Voidwalker Minion"] = true
L["Volchan"] = true
L["Vosur Brakthel"] = true
L["Waldor"] = true
L["Warmaul Shaman"] = true
L["Warped Peon"] = true
L["Wastewander Assassin"] = true
L["Wastewander Bandit"] = true
L["Wastewander Rogue"] = true
L["Wastewander Scofflaw"] = true
L["Wastewander Shadow Mage"] = true
L["Wastewander Thief"] = true
L["Weapon Technician"] = true
L["Wenna Silkbeard"] = true
L["Werg Thickblade"] = true
L["Westfall Stew"] = true
L["Whuut"] = true
L["Wik'Tar"] = true
L["Wild Hearts"] = true
L["Wild Leather Boots"] = true
L["Wild Leather Helmet"] = true
L["Wild Leather Leggings"] = true
L["Wild Leather Shoulders"] = true
L["Wild Leather Vest"] = true
L["Wilhelmina Renel"] = true
L["Wind Trader Lathrai"] = true
L["Winterfall Den Watcher"] = true
L["Winterfall Totemic"] = true
L["Winterfall Ursa"] = true
L["Witherbark Axe Thrower"] = true
L["Witherbark Berserker"] = true
L["Witherbark Headhunter"] = true
L["Witherbark Shadow Hunter"] = true
L["Withered Ancient"] = true
L["Wrahk"] = true
L["Wrath Hammer Construct"] = true
L["Wrathwalker"] = true
L["Wretched Devourer"] = true
L["Wretched Fiend"] = true
L["Wulan"] = true
L["Wulmort Jinglepocket"] = true
L["Wunna Darkmane"] = true
L["Wyrmcult Blackwhelp"] = true
L["Xandar Goodbeard"] = true
L["Xen'to"] = true
L["Xerintha Ravenoak"] = true
L["Xizzer Fizzbolt"] = true
L["Xylinnia Starshine"] = true
L["Xyrol"] = true
L["Yarr Hammerstone"] = true
L["Yatheon"] = true
L["Yelmak"] = true
L["Yonada"] = true
L["Young Black Ravager"] = true
L["Young Diemetradon"] = true
L["Young Wetlands Crocolisk"] = true
L["Ythyar"] = true
L["Yuka Screwspigot"] = true
L["Yurial Soulwater"] = true
L["Zamja"] = true
L["Zan Shivsproket"] = true
L["Zannok Hidepiercer"] = true
L["Zansoa"] = true
L["Zantasia"] = true
L["Zanzil Zombie"] = true
L["Zaralda"] = true
L["Zarena Cromwind"] = true
L["Zargh"] = true
L["Zarrin"] = true
L["Zebig"] = true
L["Zixil"] = true
L["Zorbin Fandazzle"] = true
L["Zula Slagfury"] = true
L["Zulian Tiger"] = true
L["Zurai"] = true
L["\"Cookie\" McWeaksauce"] = true

--[[

-- Common quests/drops
L["DMCACHE"] = "诺特·希姆加克的箱子"
L["Gordok Ogre Suit"] = "戈多克食人魔装"
L["Gordok Ogre Suit Obt"] = "戈多克食人魔装"
L["Spectral Essence Obt"] = "传令官基尔图诺斯 (让你能看到通灵学院附近的商人玛格努斯·霜鸣)"
L["TrueBelieverQuest"] = "真正的信徒 - 从 被破译的《真正的信徒》剪报中稀有掉落"

-- Alchemy Obtain Information
L["Discovery - Flasks/Potions"] = "领悟: 通过制作包含外域草药的合剂/药剂/药水领悟到"
L["Discovery - Protection Potions"] = "领悟: 通过制作大部分守护药剂领悟到"
L["Discovery - Transmutes"] = "领悟: 通过转化包含外域材料的物品领悟到"
L["Goblin Rocket Fuel Obt"] = "制造：这个配方是地精工程师制作出来的"
L["Gurubashi Mojo Madness Obt"] = "团队: 于祖尔格拉布的疯狂之缘区域点击石头桌子学到"
L["Mighty Trolls Blood Potion Obt"] = "训练师: 与剃刀高地的亨利·斯特恩对话"
-- Mob Drop
L["Elixir of Greater Firepower Obt"] = "黑铁奴隶贩子, 黑铁巡逻兵, 黑铁工头"
L["Elixir of the Mongoose Obt"] = "碧火盗贼, 雷加斯盗贼"
L["Elixir of the Sages Obt"] = "血色巫术师, 血色宣教士, 血色助理牧师, 血色大法师, 血色审查官"
L["Fel Mana Potion Obt"] = "日蚀士兵, 日蚀血护卫, 日蚀血骑士, 日蚀缚法者, 日蚀法师, 日蚀百夫长, 日蚀骑兵, 托洛斯, 伊利达雷监视者"
L["Fel Regeneration Potion Obt"] = "死亡熔炉小鬼, 死亡熔炉守护者, 死亡熔炉铁匠, 死亡熔炉杂役"
L["Fel Strength Elixir Obt"] = "莫尔葛武器匠, 恐怖主宰, 天罚行者, 暗影议会术士"
L["Gift of Arthas Obt"] = "骷髅剥皮者, 被奴役的食尸鬼"
L["Greater Arcane Protection Potion Obt"] = "深蓝龙人法师"
L["Greater Fire Protection Potion Obt"] = "火印祈求者, 火印炎术师"
L["Greater Frost Protection Potion Obt"] = "霜槌巨人"
L["Greater Nature Protection Potion Obt"] = "枯萎的恐兽, 腐烂的巨兽"
L["Greater Shadow Protection Potion Obt"] = "黑暗教徒, 暗影法师"
L["Major Arcane Protection Potion Obt"] = "维尔埃尼奥术师"
L["Major Fire Protection Potion Obt"] = "寻日者星术师"
L["Major Holy Protection Potion Obt"] = "深渊烈焰使者"
L["Major Shadow Protection Potion Obt"] = "暗影议会术士"
L["Mighty Rage Potion Obt"] = "黑石杀戮者"
L["Wildvine Potion Obt"] = "各种巨魔怪物"
-- Quest
L["Discolored Healing Potion Obt"] = "荒野之心"
L["Elixir of Brute Force Obt"] = "完成“达丹加饿了！”任务有机率获得"
L["Lesser Stoneshield Potion Obt"] = "卢希恩的药水"
L["Restorative Potion Obt"] = "奥达曼的蘑菇"

-- Blacksmithin Obtain Information
L["Inlaid Mithril Cylinder Obt"] = "制造：这个配方是侏儒工程师制作出来的"
L["Blacksmithing Plans"] = "从锻造配方物品随机掉落"
-- Mob Drop
L["Dark Iron Sunderer Obt"] = "持铁锤的顾客, 雷布里的亲信"
L["Felsteel Gloves Obt"] = "奥金尼僧侣"
L["Felsteel Helm Obt"] = "秘教狂热者"
L["Felsteel Leggings Obt"] = "摆脱束缚的厄运使者"
L["Frostguard Obt"] = "工头玛希瑞德"
L["Greater Ward of Shielding Obt"] = "日怒血卫士"
L["Khorium Belt Obt"] = "暗血掠夺者"
L["Khorium Boots Obt"] = "空洞的保护者"
L["Khorium Pants Obt"] = "死亡熔炉守护者"
L["Ragesteel Breastplate Obt"] = "灰舌战士"
L["Ragesteel Gloves Obt"] = "石拳战士"
L["Ragesteel Helm Obt"] = "怒火卫士"
L["Ragesteel Shoulders Obt"] = "愤怒的地灵, 愤怒的气灵, 愤怒的火灵, 愤怒的水灵"
L["Runic Breastplate Obt"] = "斯塔莎兹侍从"
L["Runic Plate Boots Obt"] = "血色骑兵"
L["Runic Plate Helm Obt"] = "斯塔莎兹战士"
L["Runic Plate Leggings Obt"] = "血色铁匠"
L["Runic Plate Shoulders Obt"] = "斯塔莎兹毒蛇守卫"
L["Swiftsteel Gloves Obt"] = "节点潜行者"
L["Volcanic Hammer Obt"] = "沃尔查"
-- Quest
L["Barbaric Iron Boots Obt"] = "踩在脚下"
L["Barbaric Iron Breastplate Obt"] = "野人装甲"
L["Barbaric Iron Gloves Obt"] = "沃姆什的喜悦"
L["Barbaric Iron Helm Obt"] = "疯狂之角"
L["Barbaric Iron Shoulders Obt"] = "铁肩铠"
L["Blazing Rapier Obt"] = "腐蚀"
L["Dawn's Edge Obt"] = "沃什加斯的蛇石"
L["Demon Forged Breastplate Obt"] = "恶魔熔炉"
L["Enchanted Battlehammer Obt"] = "甜美的平静"
L["Enchanted Thorium Breastplate Obt"] = "魔化瑟银板甲：第一卷"
L["Enchanted Thorium Helm Obt"] = "魔化瑟银板甲：第三卷"
L["Enchanted Thorium Leggings Obt"] = "魔化瑟银板甲：第二卷"
L["Fiery Plate Gauntlets Obt"] = "炽热板甲护手"
L["Golden Scale Gauntlets Obt"] = "锻造的本源"
L["Heavy Copper Longsword Obt"] = "前线的补给"
L["Imperial Plate Belt Obt"] = "君王板甲腰带"
L["Imperial Plate Boots Obt"] = "君王板甲战靴"
L["Imperial Plate Bracers Obt"] = "君王板甲护腕"
L["Imperial Plate Chest Obt"] = "君王板甲护胸"
L["Imperial Plate Helm Obt"] = "君王板甲头盔"
L["Imperial Plate Leggings Obt"] = "君王板甲护腿"
L["Imperial Plate Shoulders Obt"] = "君王板甲护肩"
L["Ironforge Breastplate Obt"] = "赤脊山的补给"
L["Orcish War Leggings Obt"] = "古老的技艺"
L["Ornate Mithril Gloves Obt"] = "白花花的银子"
L["Ornate Mithril Helm Obt"] = "铸造护甲的艺术"
L["Ornate Mithril Pants Obt"] = "铁匠必修课"
L["Ornate Mithril Shoulder Obt"] = "罩帽和护肩"
L["Sulfuron Hammer Obt"] = "瑟银兄弟会契约"

-- Cooking Obtain Information
L["Fishing Daily"] = "任务奖励: 钓鱼每日任务随机奖励"
L["Cooking Daily"] = "任务奖励: 烹饪每日任务随机奖励"
L["Goldthorn Tea Obt"] = "与剃刀高地的亨利·斯特恩对话"
L["Stewed Trout Obt"] = "训练师: 凯蕾妮"
-- Mob Drop
L["Runn Tum Tuber Surprise Obt"] = "普希林"
-- Quest
L["Barbecued Buzzard Wing Obt"] = "烧烤秃鹰翅膀"
L["Beer Basted Boar Ribs Obt"] = "啤酒烤猪排"
L["Big Bear Steak Obt"] = "拯救行动"
L["Blood Sausage Obt"] = "塞尔萨玛血肠"
L["Buzzard Bites Obt"] = "万无一失"
L["Crocolisk Gumbo Obt"] = "学徒的职责"
L["Crocolisk Steak Obt"] = "捕猎鳄鱼"
L["Crunchy Serpent Obt"] = "莫克纳萨的美味"
L["Crunchy Spider Surprise Obt"] = "松脆蜘蛛腿"
L["Curiously Tasty Omelet Obt"] = "奥莫尔的复仇"
L["Dig Rat Stew Obt"] = "掘地鼠炖肉"
L["Dirge's Kickin' Chimaerok Chops Obt"] = "迪尔格的超美味奇美拉肉片"
L["Gooey Spider Cake Obt"] = "黑蟹蛋糕"
L["Goretusk Liver Pie Obt"] = "猪肝馅饼"
L["Hot Lion Chops Obt"] = "痛苦药剂"
L["Kaldorei Spider Kabob Obt"] = "卡多雷的菜谱"
L["Murloc Fin Soup Obt"] = "卖鱼"
L["Redridge Goulash Obt"] = "赤脊山炖肉"
L["Roasted Moongraze Tenderloin Obt"] = "狩猎月痕鹿"
L["Seasoned Wolf Kabob Obt"] = "干烤狼肉串"
L["Smoked Desert Dumplings Obt"] = "沙漠食谱"
L["Soothing Turtle Bisque Obt"] = "海龟汤"
L["Strider Stew Obt"] = "炖陆行鸟"
L["Tasty Lion Steak Obt"] = "损失惨重"
L["Thistle Tea Ally Obt"] = "克拉文之塔"
L["Thistle Tea Horde Obt"] = "任务: 基本不可能的任务"
L["Westfall Stew Obt"] = "杂味炖肉"

-- Enchanting Obtain Information
L["Enchant 2H Weapon - Major Agility Obt"] = "艾瑞达死亡使者"
L["Enchant 2H Weapon - Major Intellect Obt"] = "红衣法术师"
L["Enchant 2H Weapon - Major Spirit Obt"] = "通灵学院专家"
L["Enchant 2H Weapon - Savagery Obt"] = "碎手百夫长"
L["Enchant 2H Weapon - Superior Impact Obt"] = "黑手精英"
L["Enchant Boots - Dexterity Obt"] = "暴怒的骷髅"
L["Enchant Boots - Fortitude Obt"] = "虚灵牧师"
L["Enchant Boots - Surefooted Obt"] = "幻影舞台工人"
L["Enchant Bracer - Fortitude Obt"] = "盘牙先知"
L["Enchant Bracer - Major Defense Obt"] = "复仇军消除者"
L["Enchant Bracer - Spellpower Obt"] = "血槌地卜师"
L["Enchant Bracer - Superior Strength Obt"] = "逆风术士"
L["Enchant Cloak - Greater Arcane Resistance Obt"] = "日蚀法师"
L["Enchant Cloak - Greater Shadow Resistance Obt"] = "空灵尖啸者"
L["Enchant Cloak - Lesser Agility Obt"] = "辛迪加刺客"
L["Enchant Cloak - Lesser Agility Obt1"] = "废土刺客, 废土暴徒"
L["Enchant Gloves - Advanced Herbalism Obt"] = "泥沼之王, 摩塔索恩, 沼泽漫步者, 沼泽漫步者长老, 纠缠恐兽"
L["Enchant Gloves - Advanced Mining Obt"] = "风险投资公司露天矿工"
L["Enchant Gloves - Fishing Obt"] = "斯卡基尔, 碎鳍滩行鱼人, 碎鳍智者, 碎鳍泥浆鱼人, 碎鳍潮行鱼人"
L["Enchant Gloves - Herbalism Obt"] = "疯狂的古树, 干枯的古树"
L["Enchant Gloves - Herbalism Obt1"] = "狂怒的树人, 黑色古树, 烧焦的树人"
L["Enchant Gloves - Mining Obt"] = "黑铁矮人, 黑铁爆破手, 黑铁隧道工, 黑铁破坏者, 邪恶的巴尔加拉斯"
L["Enchant Gloves - Skinning Obt"] = "屠戮者尼玛尔, 枯木狂战士, 枯木猎头者, 枯木暗影猎手"
L["Enchant Weapon - Crusader Obt"] = "血色缚法者"
L["Enchant Weapon - Crusader Obt1"] = "血色大法师"
L["Enchant Weapon - Deathfrost Obt"] = "埃霍恩领主 - 仲夏火焰节"
L["Enchant Weapon - Fiery Weapon Obt"] = "控火师罗格雷恩"
L["Enchant Weapon - Icy Chill Obt"] = "痛苦的上层精灵"
L["Enchant Weapon - Lifestealing Obt"] = "鬼灵研究员"
L["Enchant Weapon - Major Intellect Obt"] = "日怒研究员"
L["Enchant Weapon - Major Spellpower Obt"] = "巴什伊尔法术窃贼"
L["Enchant Weapon - Superior Striking Obt"] = "尖石军阀"
L["Enchant Weapon - Unholy Weapon Obt"] = "图萨丁暗影法师"
L["Smoking Heart of the Mountain Obt"] = "洛考尔"

-- Engineering Obtain Information
L["ENG_MEMBERSHIP_BENEFITS"] = "随机任务奖励：会员的奖励"
L["Field Repair Bot 74A Obt"] = "Boss身边可以点击的卷轴"
L["Minor Recombobulator Obt"] = "在矩阵打卡器3005-A上使用白色穿孔卡片，然后在矩阵打卡器3005-B上使用黄色穿孔卡片。"
L["Discombobulator Ray Obt"] = "在D机器上使用秘密数据存取卡"
-- Mob Drop
L["Adamantite Arrow Maker Obt"] = "日怒射手"
L["Arcanite Dragonling Obt"] = "深蓝龙人法师"
L["Dark Iron Rifle Obt"] = "厄炉工匠"
L["Felsteel Boomstick Obt"] = "末日熔炉技师"
L["Field Repair Bot 110G Obt"] = "甘尔葛分析师"
L["Flawless Arcanite Rifle Obt"] = "烂苔暗影猎手"
L["Hyper-Vision Goggles Obt"] = "莫尔葛武器匠"
L["Khorium Scope Obt"] = "日怒弓箭手"
L["Major Recombobulator Obt"] = "戈多克的贡品箱子"
L["Weapon Technician"] = "武器技师"
L["Crimson Inquisitor"] = "红衣审查者"
-- Quest
L["Flash Bomb Obt"] = "闪光弹的制法"
L["Steam Tonk Controller Obt"] = "40张奖券 - 高级奖品 (暗月马戏团)"
L["Zapthrottle Mote Extractor Obt"] = "气阀微粒提取器!"

-- First Aid Obtain Information
-- Nothing here needed yet

-- Jewelcrafting Obtain Information
L["Blades Edge Summon Bosses"] = "奥格瑞拉召唤的首领"
-- Mob Drop
L["Arcane Khorium Band Obt"] = "法师杀手"
L["Chaotic Skyfire Diamond Obt"] = "库斯卡女妖"
L["Coronet of the Verdant Flame Obt"] = "寻日者植物学家"
L["Khorium Band of Frost Obt"] = "盘牙巫师"
L["Khorium Band of Leaves Obt"] = "维克鸦巢恐怖卫士"
L["Khorium Band of Shadows Obt"] = "黑暗教团暗影法师"
-- Quest

-- Leatheworking Obtain Information
-- Mob Drop
L["Bag of Many Hides Obt"] = "戈杜尼断脊者, 戈杜尼劈颅者, 戈杜尼元素师, 戈杜尼裂魂者"
L["Anvilrage Captain"] = "铁怒上尉"
L["Blue Dragonscale Shoulders Obt"] = "峭壁击碎者"
L["Devilsaur Leggings Obt"] = "克隆软泥怪, 胶质软泥怪"
L["Flame Armor Kit Obt"] = "巨型深渊火魔"
L["Frostsaber Gloves Obt"] = "冬泉图腾师"
L["Frostsaber Leggings Obt"] = "冬泉巢穴守卫"
L["Frostsaber Tunic Obt"] = "冬泉巨熊怪"
L["Green Dragonscale Leggings Obt"] = "黑暗虫"
L["Heavy Scorpid Leggings Obt"] = "黑石杀戮者"
L["Heavy Scorpid Shoulders Obt"] = "黑石军官"
L["Heavy Scorpid Vest Obt"] = "传送门搜寻者"
L["Ironfeather Breastplate Obt"] = "邪枝剥皮者"
L["Living Breastplate Obt"] = "枯萎的恐兽"
L["Living Leggings Obt"] = "死木萨满祭司"
L["Shadow Armor Kit Obt"] = "迷失的暗影法师"
L["Stormshroud Armor Obt"] = "亚考兰智者"
L["Stormshroud Gloves Obt"] = "烈风掠夺者"
L["Stormshroud Gloves Obt1"] = "泰比斯蒂亚公主, 冬泉谷"
L["Stormshroud Shoulders Obt"] = "亚考罗克之子"
L["Stylin' Adventure Hat Obt"] = "敦霍尔德火枪手"
L["Stylin' Crimson Hat Obt"] = "塞泰克鸦人卫士"
L["Stylin' Jungle Hat Obt"] = "裂隙领主, 裂隙守卫者"
L["Tough Scorpid Boots Obt"] = "废土游荡者"
L["Tough Scorpid Bracers Obt"] = "废土暗法师"
L["Tough Scorpid Breastplate Obt"] = "废土强盗"
L["Tough Scorpid Gloves Obt"] = "废土窃贼"
L["Tough Scorpid Helm Obt"] = "安德雷·费尔比德, 废土暴徒"
L["Tough Scorpid Leggings Obt"] = "废土游荡者"
L["Volcanic Breastplate Obt"] = "火印步兵"
L["Volcanic Leggings Obt"] = "火腹蛮兵"
L["Volcanic Shoulders Obt"] = "火印军团战士"
-- Quest
L["Deviate Scale Belt Obt"] = "清除变异者"
L["Kodo Hide Bag Obt"] = "科多兽皮包"
L["Moonglow Vest Obt"] = "月光外衣"
L["Onyxia Scale Cloak Obt"] = "一切才刚刚开始 (上交奥妮克西亚头颅后)"
L["Wild Leather Boots Obt"] = "蛮皮战靴"
L["Wild Leather Cloak Obt"] = "蛮皮护甲大师"
L["Wild Leather Helmet Obt"] = "蛮皮头盔"
L["Wild Leather Leggings Obt"] = "蛮皮护腿"
L["Wild Leather Shoulders Obt"] = "蛮皮护肩"
L["Wild Leather Vest Obt"] = "蛮皮外衣"

-- Smelting Obtain Information
L["Dark Iron Obt"] = "需要20个金锭, 2个红宝石, 10个真银锭, 跟黑石深渊七贤处的格鲁雷尔对话"
L["Elementium Obt"] = "精神控制BWL大元素师克里希克，使用宠物栏一个技能学得"

-- Rogue Poison Obtain Information
-- Nothing here needed yet

-- Tailoring Obtain Information
L["Arcanoweave Boots Obt"] = "寻日者星术师"
L["Arcanoweave Bracers Obt"] = "禁魔监狱斥候"
L["Black Silk Pack Obt"] = "辛迪加间谍"
L["Black Silk Pack Obt1"] = "塞拉摩间谍"
L["Black Silk Pack Obt2"] = "暗影刺客"
L["Cindercloth Cloak Obt"] = "索瑞森驭火者"
L["Cindercloth Gloves Obt"] = "暮光火焰卫士"
L["Cindercloth Pants Obt"] = "索瑞森驭火者"
L["Cindercloth Vest Obt"] = "暮光火焰卫士"
L["Cloak of Fire Obt"] = "征服者派隆"
L["Felcloth Bag Obt"] = "杀死詹迪斯·巴罗夫后出现的书中获得"
L["Ghostweave Belt Obt"] = "徘徊的上层精灵"
L["Ghostweave Gloves Obt"] = "徘徊的上层精灵"
L["Ghostweave Gloves Obt1"] = "无影仆从"
L["Ghostweave Vest Obt"] = "无影仆从"
L["Mooncloth Boots Obt"] = "神圣的月布"
L["Robe of the Archmage Obt"] = "火印炎术师"
L["Robe of Winter Night Obt"] = "深蓝龙人法师"
L["Robes of Arcana Obt"] = "暗滩唤魔师"
L["Robes of Arcana Obt1"] = "迪菲亚附魔师"
L["Shadoweave Mask Obt"] = "黑市交易"
L["Soulcloth Shoulders Obt"] = "幻影随从"
L["Soulcloth Vest Obt"] = "幻影仆从"
L["Wizardweave Leggings Obt"] = "黑暗召唤师"

-- Beast Training Obtain Information
L["Rare"] = "稀有"
L["Elite"] = "精英"
-- Beasts which have training skills Localized by 冰焱妩魅 @ CWDG
L["Agam'ar"] = "阿迦玛"
L["Aku'mai Fisher"] = "阿库麦尔食鱼龟"
L["Aku'mai Snapjaw"] = "阿库麦尔钳嘴龟"
L["Angerclaw Mauler"] = "怒爪巨熊"
L["Arash-ethis"] = "阿拉瑟希斯"
L["Ashenvale Bear"] = "灰谷熊"
L["Ashmane Boar"] = "灰鬃野猪"
L["Barbed Crustacean"] = "刺毛甲壳蟹"
L["Barnabus"] = "巴纳布斯"
L["Battleboar"] = "斗猪"
L["Bellygrub"] = "贝利格拉布"
L["Besseleth"] = "贝瑟莱斯"
L["Bhag'thera"] = "巴尔瑟拉"
L["Bjarn"] = "游荡的冰爪熊"
L["Black Bear Patriarch"] = "黑熊首领"
L["Black Ravager Mastiff"] = "巨型黑色破坏者"
L["Black Ravager"] = "黑色破坏者"
L["Blackrock Worg"] = "黑石座狼"
L["Blackwind Warp Chaser"] = "黑风追迹者"
L["Blisterpaw Hyena"] = "疱爪土狼"
L["Bloodaxe Worg"] = "血斧座狼"
L["Bloodfalcon"] = "血隼"
L["Bloodmaul Battle Worg"] = "血槌战斗座狼"
L["Bloodmaul Dire Wolf"] = "血槌巨狼"
L["Bloodsnout Worg"] = "血牙座狼"
L["Bonepaw Hyena"] = "骨爪土狼"
L["Bristleback Battleboar"] = "刺背斗猪"
L["Broken Tooth"] = "断牙"
L["Carrion Vulture"] = "食腐秃鹫"
L["Cave Creeper"] = "洞穴爬行者"
L["Chatter"] = "查特"
L["Clack the Reaver"] = "掠夺者科拉克"
L["Clattering Crawler"] = "巨钳蟹"
L["Cleft Scorpid"] = "裂隙沙漠蝎"
L["Cloud Serpent"] = "风蛇"
L["Cobalt Serpent"] = "蓝色毒蛇"
L["Coilskar Cobra"] = "库斯卡眼镜蛇"
L["Corrupted Mottled Boar"] = "堕落的杂斑野猪"
L["Corrupted Scorpid"] = "堕落蝎"
L["Coyote Packleader"] = "山狗首领"
L["Coyote"] = "山狗"
L["Crag Boar"] = "峭壁野猪"
L["Crag Coyote"] = "峭壁山狗"
L["Crag Stalker"] = "峭壁捕猎者"
L["Crazed Dragonhawk"] = "疯狂的龙鹰"
L["Creepthess"] = "克雷普塞斯"
L["Dark Screecher"] = "黑暗尖啸者"
L["Dark Worg"] = "黑暗座狼"
L["Darkfang Creeper"] = "暗牙爬行者"
L["Deadly Cleft Scorpid"] = "致命的裂隙沙漠蝎"
L["Deadmire"] = "死沼巨鳄"
L["Death Flayer"] = "死亡毒蝎"
L["Death Howl"] = "死亡之嚎"
L["Deathlash Scorpid"] = "死鞭蝎"
L["Deathstrike Tarantula"] = "死亡狼蛛"
L["Deep Stinger"] = "深渊钉刺者"
L["Deepmoss Creeper"] = "深苔爬行者"
L["Deepmoss Webspinner"] = "深苔结网蛛"
L["Den Mother"] = "雌蓟熊"
L["Deviate Adder"] = "无毒飞蛇"
L["Deviate Coiler Hatchling"] = "变异风蛇幼崽"
L["Deviate Coiler"] = "变异曲蛇"
L["Deviate Crocolisk"] = "变异鳄鱼"
L["Deviate Dreadfang"] = "变异尖牙风蛇"
L["Deviate Moccasin"] = "弱毒飞蛇"
L["Deviate Stinglash"] = "变异刺鞭蛇"
L["Deviate Venomwing"] = "变异剧毒风蛇"
L["Deviate Viper"] = "剧毒飞蛇"
L["Dire Mottled Boar"] = "可怕的杂斑野猪"
L["Diseased Grizzly"] = "生病的灰熊"
L["Diseased Wolf"] = "生病的狼"
L["Dread Flyer"] = "恐怖飞鸟"
L["Dread Ripper"] = "恐怖撕裂者"
L["Dreadfang Lurker"] = "巨牙潜伏者"
L["Dreadfang Widow"] = "巨牙寡妇蛛"
L["Dreadmaw Crocolisk"] = "巨齿鳄鱼"
L["Drywallow Crocolisk"] = "尘泥鳄鱼"
L["Drywallow Daggermaw"] = "尘泥利齿鳄鱼"
L["Drywallow Snapper"] = "尘泥钳嘴鳄鱼"
L["Durotar Tiger"] = "杜隆塔尔猛虎"
L["Eclipsion Dragonhawk"] = "日蚀龙鹰"
L["Elder Ashenvale Bear"] = "老灰谷熊"
L["Elder Cloud Serpent"] = "老风蛇"
L["Elder Crag Boar"] = "老峭壁野猪"
L["Elder Crag Coyote"] = "老峭壁山狗"
L["Elder Mistvale Gorilla"] = "老迈的薄雾谷猩猩"
L["Elder Moss Creeper"] = "老食苔蛛"
L["Elder Mottled Boar"] = "老杂斑野猪"
L["Elder Mountain Boar"] = "老山猪"
L["Elder Plainstrider"] = "老平原陆行鸟"
L["Elder Shadowmaw Panther"] = "老年深喉猎豹"
L["Elder Shardtooth"] = "老碎齿熊"
L["Elder Springpaw"] = "老魔泉豹"
L["Encrusted Surf Crawler"] = "硬壳海浪蟹"
L["Enraged Ravager"] = "被激怒的掠食者"
L["Felpaw Ravager"] = "魔爪掠夺者"
L["Felpaw Wolf"] = "魔爪狼"
L["Felsworn Scalewing"] = "魔誓鳞翼风蛇"
L["Feral Crag Coyote"] = "野生峭壁山狗"
L["Feral Dragonhawk Hatchling"] = "龙鹰雏鸟"
L["Feral Mountain Lion"] = "野生山地狮"
L["Ferocious Grizzled Bear"] = "凶猛的灰斑熊"
L["Fire Roc"] = "火鹏"
L["Firetail Scorpid"] = "火尾蝎"
L["Flatland Cougar"] = "平原狮"
L["Fleeting Plainstrider"] = "敏捷的平原陆行鸟"
L["Forest Lurker"] = "森林潜伏者"
L["Forest Moss Creeper"] = "森林食苔蛛"
L["Forest Spider"] = "森林蜘蛛"
L["Foreststrider Fledgling"] = "森林陆行鸟雏鸟"
L["Frostsaber Cub"] = "霜刃豹幼崽"
L["Frostsaber Huntress"] = "霜刃雌豹"
L["Frostsaber Stalker"] = "霜刃捕食者"
L["Ghamoo-ra"] = "加摩拉"
L["Ghost Saber"] = "幽灵豹"
L["Ghostclaw Lynx"] = "鬼爪山猫"
L["Ghostclaw Ravager"] = "鬼爪破坏者"
L["Ghostpaw Alpha"] = "幽爪前锋"
L["Ghostpaw Runner"] = "幽爪奔跑者"
L["Giant Foreststrider"] = "凶猛的森林陆行鸟"
L["Giant Moss Creeper"] = "巨型食苔蛛"
L["Giant Plains Creeper"] = "巨型平原狼蛛"
L["Giant Webwood Spider"] = "巨型树林蜘蛛"
L["Giant Wetlands Crocolisk"] = "巨型湿地鳄鱼"
L["Githyiss the Vile"] = "邪恶的基塞伊斯"
L["Goretusk"] = "血牙野猪"
L["Gray Bear"] = "灰熊"
L["Gray Forest Wolf"] = "森林灰狼"
L["Great Goretusk"] = "巨型血牙野猪"
L["Greater Duskbat"] = "巨型夜行蝙蝠"
L["Greater Firebird"] = "巨型火鸟"
L["Greater Fleshripper"] = "大碎尸鸟"
L["Greater Kraul Bat"] = "巨型沼泽蝙蝠"
L["Greater Tarantula"] = "巨型狼蛛"
L["Greater Thunderhawk"] = "大型雷鹰"
L["Greater Windroc"] = "大型风鹏"
L["Green Recluse"] = "绿色独行蛛"
L["Groddoc Thunderer"] = "格罗多克大猩猩"
L["Grovestalker Lynx "] = "林地山猫"
L["Grunter"] = "格朗特"
L["Gutripper"] = "裂肠者"
L["Hakkar'i Frostwing"] = "哈卡莱霜翼飞蛇"
L["Hakkar'i Sapper"] = "哈卡莱挖掘者"
L["Ice Claw Bear"] = "冰爪熊"
L["Ironback"] = "铁背龟"
L["Ironbeak Hunter"] = "铁喙狩猎者"
L["Ironbeak Owl"] = "铁喙猫头鹰"
L["Ironbeak Screecher"] = "铁喙尖啸者"
L["Ironfur Bear"] = "铁鬃熊"
L["Ironfur Patriarch"] = "铁鬃熊王"
L["Jaguero Stalker"] = "丛林猎豹"
L["Jungle Thunderer"] = "丛林大猩猩"
L["Juvenile Snow Leopard"] = "雪豹幼崽"
L["Kaliri Matriarch"] = "卡利鸟女王"
L["Kaliri Swooper"] = "卡利鸟飞扑者"
L["King Bangalash"] = "虎王邦加拉什"
L["Kraul Bat"] = "沼泽蝙蝠"
L["Krellack"] = "克里拉克"
L["Kresh"] = "克雷什"
L["Kurzen War Tiger"] = "库尔森战虎"
L["Lady Sathrah"] = "萨丝拉"
L["Large Crag Boar"] = "大峭壁野猪"
L["Large Loch Crocolisk"] = "大型洛克鳄"
L["Leech Widow"] = "吸血寡妇"
L["Loch Crocolisk"] = "洛克鳄"
L["Longsnout"] = "长鼻野猪"
L["Longtooth Howler"] = "长牙嚎叫者"
L["Longtooth Runner"] = "长牙奔跑者"
L["Lost Torranche"] = "迷失的步行鸟"
L["Lupos"] = "鲁伯斯s"
L["Magram Bonepaw"] = "玛格拉姆骨爪土狼"
L["Male Kaliri Hatchling"] = "雄性小卡利鸟"
L["Mangeclaw"] = "癞爪"
L["Mangy Mountain Boar"] = "癞皮山猪"
L["Mazzranache"] = "马兹拉纳其"
L["Mesa Buzzard"] = "山地秃鹰"
L["Mist Howler"] = "迷雾嚎叫者"
L["Mistvale Gorilla"] = "薄雾谷猩猩"
L["Mongress"] = "莫戈雷斯"
L["Monstrous Crawler"] = "巨型淤泥蟹"
L["Monstrous Plaguebat"] = "巨型瘟疫蝙蝠"
L["Moonstalker Runt"] = "月夜猛虎幼崽"
L["Moonstalker Sire"] = "月夜雄虎"
L["Mottled Boar"] = "杂斑野猪"
L["Mottled Drywallow Crocolisk"] = "尘泥杂斑鳄鱼"
L["Mountain Boar"] = "山猪"
L["Mountain Lion"] = "山地狮"
L["Mudrock Snapjaw"] = "泥石钳嘴龟"
L["Murk Slitherer"] = "黑暗滑行虫"
L["Murk Spitter"] = "黑暗粘液虫"
L["Naraxis"] = "纳拉克西斯"
L["Night Web Matriarch"] = "夜行雌蜘蛛"
L["Night Web Spider"] = "夜行蜘蛛"
L["Nightsaber"] = "夜刃豹"
L["Noxious Plaguebat"] = "毒性瘟疫蝙蝠"
L["Oasis Snapjaw"] = "绿洲钳嘴龟"
L["Ol' Sooty"] = "奥尔苏迪"
L["Old Cliff Jumper"] = "海崖奔跳者"
L["Old Grizzlegut"] = "灰腹老熊"
L["Olm the Wise"] = "智者奥尔姆"
L["Ornery Plainstrider"] = "暴躁的平原陆行鸟"
L["Panther"] = "黑豹"
L["Phoenix-Hawk Hatchling"] = "凤鹰幼崽"
L["Plague Lurker"] = "瘟疫潜伏者"
L["Plaguebat"] = "瘟疫蝙蝠"
L["Plagued Swine"] = "瘟疫野猪"
L["Plains Creeper"] = "平原狼蛛"
L["Porcine Entourage"] = "公主的随从"
L["Prairie Stalker"] = "草原捕食者"
L["Prairie Wolf Alpha"] = "草原狼前锋"
L["Prairie Wolf"] = "草原狼"
L["Princess"] = "公主"
L["Prowler"] = "觅食的灰狼"
L["Pygmy Surf Crawler"] = "小海浪蟹"
L["Quillfang Ravager"] = "钢牙掠食者"
L["Quillfang Skitterer"] = "钢牙飞掠者"
L["Rabid Blisterpaw"] = "疯狂的疱爪土狼"
L["Rabid Crag Coyote"] = "疯狂的峭壁山狗"
L["Ragged Scavenger"] = "蓬毛食腐狼"
L["Raging Agam'ar"] = "暴怒的阿迦玛"
L["Rak'Shiri"] = "拉克西里"
L["Ravage"] = "毁灭"
L["Ravager Specimen"] = "成型的掠食者"
L["Ravenous Windroc"] = "饥饿的风鹏"
L["Razorfang Hatchling"] = "刃齿幼崽"
L["Razzashi Adder"] = "拉扎什蝰蛇"
L["Razzashi Cobra"] = "拉扎什眼镜蛇"
L["Razzashi Serpent"] = "拉扎什毒蛇"
L["Rekk'tilac"] = "雷克提拉克"
L["Rema"] = "雷玛"
L["Ridge Huntress"] = "山脊雌豹"
L["Ridge Stalker Patriarch"] = "山脊雄豹"
L["Ridge Stalker"] = "山脊巡行者"
L["Rip-Blade Ravager"] = "裂刃剥石者"
L["Ripfang Lynx"] = "锋牙山猫"
L["Ripscale"] = "雷普斯凯尔"
L["Roc"] = "大鹏"
L["Rockhide Boar"] = "石皮野猪"
L["Rogue Vale Screecher"] = "游荡的山谷尖啸者"
L["Rotting Agam'ar"] = "腐烂的阿迦玛"
L["Salt Flats Vulture"] = "盐湖秃鹫"
L["Saltwater Snapjaw"] = "海水钳嘴龟"
L["Sandfury Guardian"] = "沙怒守护者"
L["Sarkoth"] = "萨科斯"
L["Savannah Patriarch"] = "草原狮王"
L["Sawtooth Snapper"] = "盐齿钳嘴鳄"
L["Scalewing Serpent"] = "鳞翼飞蛇"
L["Scarlet Tracking Hound"] = "血色捕猎犬"
L["Scarred Crag Boar"] = "有伤疤的峭壁野猪"
L["Scarshield Worg"] = "裂盾座狼"
L["Scorchshell Pincer"] = "灼壳蝎"
L["Scorpashi Lasher"] = "荒土鞭尾蝎"
L["Scorpashi Snapper"] = "荒土巨钳蝎"
L["Scorpashi Venomlash"] = "荒土毒尾蝎"
L["Scorpid Bonecrawler"] = "噬骨蝎"
L["Scorpid Duneburrower"] = "沙漠掘洞蝎"
L["Scorpid Dunestalker"] = "沙漠疾行蝎"
L["Scorpid Hunter"] = "沙漠猎食蝎"
L["Scorpid Reaver"] = "恐蝎劫掠者"
L["Scorpid Tail Lasher"] = "沙漠鞭尾蝎"
L["Scorpid Terror"] = "恐蝎"
L["Scorpid Worker"] = "蝎子"
L["Scorpok Stinger"] = "厚甲毒刺蝎"
L["Searing Roc"] = "炎鹏"
L["Shadow Panther"] = "暗影黑豹"
L["Shadowmaw Panther"] = "深喉猎豹"
L["Shadowwing Owl"] = "暗翼猫头鹰"
L["Shanda the Spinner"] = "纺织者杉达"
L["Shardtooth Bear"] = "碎齿熊"
L["Shore Crawler"] = "滩行蟹"
L["Shrike Bat"] = "利齿蝙蝠"
L["Silithid Creeper"] = "异种爬行者"
L["Silithid Swarmer"] = "异种群居蝎"
L["Silt Crawler"] = "淤泥蟹"
L["Silvermane Howler"] = "银鬃嗥狼"
L["Silvermane Stalker"] = "银鬃捕猎者"
L["Silvermane Wolf"] = "银鬃狼"
L["Sin'Dall"] = "辛达尔"
L["Skettis Kaliri"] = "斯克提斯卡利鸟"
L["Skittering Crustacean"] = "滑腻的甲壳蟹"
L["Small Crag Boar"] = "小型峭壁野猪"
L["Snapjaw"] = "钳嘴龟"
L["Snapping Crustacean"] = "巨钳甲壳蟹"
L["Snarler"] = "咆哮者"
L["Snow Tracker Wolf"] = "雪狼"
L["Son of Hakkar"] = "哈卡之子"
L["Soulflayer"] = "灵魂掠夺者"
L["Sparkleshell Snapper"] = "盐壳钳嘴龟"
L["Spawn of Hakkar"] = "哈卡的后代"
L["Spiteflayer"] = "斯比弗雷尔"
L["Spot"] = "斑斑"
L["Starving Blisterpaw"] = "饥饿的疱爪土狼"
L["Starving Mountain Lion"] = "饥饿的山地狮"
L["Starving Winter Wolf"] = "饥饿的冬狼"
L["Stonelash Flayer"] = "石鞭掠夺者"
L["Stonelash Pincer"] = "石鞭巨钳蝎"
L["Stonelash Scorpid"] = "石鞭蝎"
L["Stonetusk Boar"] = "石牙野猪"
L["Stranglethorn Tiger"] = "荆棘谷猛虎"
L["Strigid Hunter"] = "巨翼猎枭"
L["Strigid Owl"] = "巨翼枭"
L["Swamp Jaguar"] = "沼泽虎"
L["Swiftwing Shredder"] = "迅翼撕裂者"
L["Tarantula"] = "狼蛛"
L["Thistle Bear"] = "蓟熊"
L["Thistle Boar"] = "草刺野猪"
L["Thornfang Ravager"] = "棘牙掠食者"
L["Thornfang Venomspitter"] = "棘牙喷毒者"
L["Thunderhawk Cloudscraper"] = "雷鹰破云者"
L["Thunderhawk Hatchling"] = "雷鹰雏鸟"
L["Tide Crawler"] = "潮行蟹"
L["Timber Worg"] = "森林座狼"
L["Timber"] = "狂暴的冬狼"
L["Timberweb Recluse"] = "林木隐匿者"
L["Twilight Runner"] = "夜行虎"
L["U'cha"] = "尤尔查"
L["Uhk'loc"] = "乌卡洛克"
L["Un'Goro Thunderer"] = "安戈洛大猩猩"
L["Vale Screecher"] = "山谷尖啸者"
L["Venomlash Scorpid"] = "毒鞭蝎"
L["Venomous Cloud Serpent"] = "毒性风蛇"
L["Venomtail Scorpid"] = "毒尾蝎"
L["Venomtip Scorpid"] = "毒尖蝎"
L["Vicious Night Web Spider"] = "邪恶的夜行蜘蛛"
L["Vile Sting"] = "邪刺恐蝎"
L["Vilebranch Raiding Wolf"] = "邪枝巨狼"
L["Warp Chaser"] = "迁跃追迹者"
L["Warp Hunter"] = "迁跃猎手"
L["Warp Stalker"] = "迁跃捕猎者"
L["Washte Pawne"] = "瓦希塔帕恩"
L["Wayward Buzzard"] = "游荡的秃鹫"
L["Webwood Silkspinner"] = "树林结网蛛"
L["Webwood Venomfang"] = "树林毒蜘蛛"
L["Wildthorn Lurker"] = "野棘潜伏者"
L["Windroc Hunter"] = "雄性狩猎风鹏"
L["Windroc Huntress"] = "雌性狩猎风鹏"
L["Windroc Matriarch"] = "风鹏皇后"
L["Windroc"] = "风鹏"
L["Winter Wolf"] = "冬狼"
L["Winterspring Owl"] = "冬泉巨枭"
L["Winterspring Screecher"] = "冬泉鸣枭"
L["Wood Lurker"] = "林木潜伏者"
L["Worg"] = "座狼"
L["Young Forest Bear"] = "森林熊幼崽"
L["Young Goretusk"] = "幼年血牙野猪"
L["Young Mesa Buzzard"] = "山地秃鹰幼崽"
L["Young Panther"] = "猎豹幼崽"
L["Young Stranglethorn Tiger"] = "荆棘谷猛虎幼崽"
L["Young Thistle Boar"] = "草刺野猪幼崽"
L["Zaricotl"] = "扎里科特"
L["Zulian Panther"] = "祖利安雌猎虎"
L["Zulian Stalker"] = "祖利安捕猎者"

-- Vendor Names Localized by 冰焱妩魅 @ CWDG
L["Aaron Hollman"] = "埃隆·霍尔曼"
L["Abigail Shiel"] = "阿比盖尔·沙伊尔"
L["Aged Dalaran Wizard"] = "老迈的达拉然巫师"
L["Alchemist Gribble"] = "炼金师格里比"
L["Alchemist Pestlezugg"] = "炼金师匹斯特苏格"
L["Aldraan"] = "阿尔德兰"
L["Alexandra Bolero"] = "亚历山德拉·波利罗"
L["Algernon"] = "奥格诺恩"
L["Altaa"] = "奥泰恩"
L["Amy Davenport"] = "艾米·达文波特"
L["Andrew Hilbert"] = "安德鲁·希尔伯特"
L["Andrion Darkspinner"] = "安迪恩·达克斯宾"
L["Androd Fadran"] = "安多德·法德兰"
L["Apothecary Antonivich"] = "药剂师安东尼维奇"
L["Aresella"] = "阿蕾瑟拉"
L["Arras"] = "阿尔拉斯"
L["Arred"] = "阿尔雷德"
L["Arrond"] = "阿隆德"
L["Asarnan"] = "阿萨纳"
L["Balai Lok'Wein"] = "巴莱·洛克维"
L["Bale"] = "拜尔"
L["Banalash"] = "巴纳拉什"
L["Blimo Gadgetspring"] = "布里莫"
L["Blixrez Goodstitch"] = "布里克雷兹·古斯提"
L["Blizrik Buckshot"] = "布雷兹里克·巴克舒特"
L["Bliztik"] = "布里兹提克"
L["Bombus Finespindle"] = "伯布斯·钢轴"
L["Borto"] = "波尔图"
L["Borya"] = "博亚"
L["Brienna Starglow"] = "布琳娜·星光"
L["Bro'kin"] = "布洛金"
L["Bronk"] = "布隆克"
L["Burbik Gearspanner"] = "巴比克·齿轮"
L["Burko"] = "布尔库"
L["Captured Gnome"] = "被俘虏的侏儒"
L["Catherine Leland"] = "凯瑟琳·利兰"
L["Christoph Jeffcoat"] = "克里斯托弗·杰弗寇特"
L["Clyde Ranthal"] = "克莱德·兰萨尔"
L["Constance Brisboise"] = "康斯坦茨·布里斯博埃斯"
L["Cookie McWeaksauce"] = "“曲奇”米维克索斯"
L["Cookie One-Eye"] = "独眼曲奇"
L["Coreiel"] = "克蕾伊尔"
L["Corporal Bluth"] = "布鲁斯下士"
L["Cowardly Crosby"] = "怯懦的克罗斯比"
L["Crazk Sparks"] = "克拉赛·斯巴克斯"
L["Cro Threadstrong"] = "克鲁·粗线"
L["Daga Ramba"] = "达加·拉姆巴"
L["Daggle Ironshaper"] = "达格尔·塑铁"
L["Dalria"] = "达利亚"
L["Daniel Bartlett"] = "丹尼尔·巴特莱特"
L["Danielle Zipstitch"] = "丹尼勒·希普斯迪"
L["Darian Singh"] = "达利安·辛格"
L["Darnall"] = "旅店老板达纳尔"
L["Dealer Malij"] = "商人玛里耶"
L["Defias Profiteer"] = "迪菲亚奸商"
L["Deneb Walker"] = "德尼布·沃克"
L["Derak Nightfall"] = "德拉克·奈特弗"
L["Deynna"] = "德伊娜"
L["Dirge Quikcleave"] = "迪尔格·奎克里弗"
L["Doba"] = "度巴"
L["Drac Roughcut"] = "德拉克·卷刃"
L["Drake Lindgren"] = "德拉克·林格雷"
L["Drovnar Strongbrew"] = "德鲁纳·烈酒"
L["Edna Mullby"] = "巴比克·齿轮"
L["Egomis"] = "艾苟米斯"
L["Eiin"] = "伊恩"
L["Elynna"] = "艾琳娜"
L["Emrul Riknussun"] = "埃姆鲁尔·里克努斯"
L["Eriden"] = "恩里德"
L["Erika Tate"] = "艾瑞卡·塔特"
L["Erilia"] = "艾瑞丽亚"
L["Feera"] = "菲拉"
L["Felannia"] = "菲兰妮娅"
L["Felicia Doan"] = "菲利希亚·杜安"
L["Felika"] = "菲利卡"
L["Fradd Swiftgear"] = "弗拉德"
L["Fyldan"] = "菲尔丹"
L["Gagsprocket"] = "加格斯普吉特"
L["Gambarinka"] = "加巴林卡"
L["Gearcutter Cogspinner"] = "考格斯宾"
L["Gelanthis"] = "基兰希斯"
L["George Candarte"] = "乔治·坎达特"
L["Gharash"] = "卡尔拉什"
L["Ghok'kah"] = "格鲁克卡恩"
L["Gidge Spellweaver"] = "金吉·斯比维尔"
L["Gigget Zipcoil"] = "吉盖特·火油"
L["Gikkix"] = "吉科希斯"
L["Gina MacGregor"] = "吉娜·马克葛瑞格"
L["Gloria Femmel"] = "格劳瑞亚·菲米尔"
L["Glyx Brewright"] = "格里克斯·布鲁维特"
L["Gnaz Blunderflame"] = "格纳兹·枪焰"
L["Gretta Ganter"] = "格雷塔·甘特"
L["Grimtak"] = "格瑞姆塔克"
L["Haalrun"] = "海尔伦"
L["Haferet"] = "哈弗雷特"
L["Hagrus"] = "哈格鲁斯"
L["Hammon Karwn"] = "哈蒙·卡文"
L["Harggan"] = "哈尔甘"
L["Harklan Moongrove"] = "哈克兰·月林"
L["Harlown Darkweave"] = "哈鲁恩·暗纹"
L["Harn Longcast"] = "哈恩·长线"
L["Haughty Modiste"] = "傲慢的店主"
L["Heldan Galesong"] = "海尔丹·风歌"
L["Helenia Olden"] = "海伦妮亚·奥德恩"
L["Himmik"] = "西米克"
L["Hula'mahi"] = "哈拉玛"
L["Innkeeper Biribi"] = "旅店老板贝莉比"
L["Innkeeper Fizzgrimble"] = "旅店老板菲兹格瑞博"
L["Innkeeper Grilka"] = "旅店老板格里尔卡"
L["Jabbey"] = "加贝"
L["Jandia"] = "詹迪亚"
L["Janet Hommers"] = "詹奈特·霍莫斯"
L["Jangdor Swiftstrider"] = "杉多尔·迅蹄"
L["Jannos Ironwill"] = "加诺斯·铁心"
L["Jaquilina Dramet"] = "加奎琳娜·德拉米特"
L["Jase Farlane"] = "贾斯·法拉恩"
L["Jazzrik"] = "加兹里克"
L["Jeeda"] = "基达"
L["Jennabink Powerseam"] = "吉娜比克·铁线"
L["Jessara Cordell"] = "杰萨拉·考迪尔"
L["Jim Saltit"] = "吉姆·萨迪特"
L["Jinky Twizzlefixxit"] = "金克·铁钩"
L["Johan Barnes"] = "乔汉·巴内斯"
L["Joseph Moore"] = "约瑟夫·摩尔"
L["Jubie Gadgetspring"] = "朱比"
L["Jun'ha"] = "祖恩哈"
L["Juno Dufrain"] = "基诺·杜弗莱"
L["Jutak"] = "祖塔克"
L["Kaita Deepforge"] = "凯塔·深炉"
L["Kalaen"] = "卡莱恩"
L["Kalldan Felmoon"] = "卡尔丹·暗月"
L["Kania"] = "卡妮亚"
L["Keena"] = "基纳"
L["Kelsey Yance"] = "凯尔希·杨斯"
L["Kendor Kabonka"] = "肯多尔·卡邦卡"
L["Khara Deepwater"] = "卡拉·深水"
L["Kiknikle"] = "吉克尼库"
L["Killian Sanatha"] = "基利恩·萨纳森"
L["Kilxx"] = "基尔克斯"
L["Kireena"] = "基瑞娜"
L["Kithas"] = "基萨斯"
L["Knaz Blunderflame"] = "克纳兹·枪焰"
L["Kor'geld"] = "考吉尔德"
L["Krek Cragcrush"] = "克雷格·碎岩"
L["Kriggon Talsone"] = "克雷贡·塔尔松"
L["Krinkle Goodsteel"] = "克林科·古德斯迪尔"
L["Kulwia"] = "库尔维亚"
L["Kzixx"] = "卡兹克斯"
L["Laird"] = "莱尔德"
L["Landraelanis"] = "兰达兰尼斯"
L["Lardan"] = "拉尔丹"
L["Lebowski"] = "莱布斯基"
L["Leeli Longhaggle"] = "莉莉·朗哈格"
L["Leo Sarn"] = "雷欧·萨恩"
L["Leonard Porter"] = "莱纳德·波特"
L["Lilly"] = "莉蕾"
L["Lindea Rabonne"] = "林迪·拉波尼"
L["Lizbeth Cromwell"] = "莉兹白·克伦威尔"
L["Logannas"] = "洛加纳斯"
L["Loolruna"] = "卢尔鲁娜"
L["Lorelae Wintersong"] = "罗莱尔·冬歌"
L["Lyna"] = "琳娜"
L["Madame Ruby"] = "卢比夫人"
L["Mahu"] = "曼胡"
L["Mallen Swain"] = "玛林·斯万"
L["Malygen"] = "玛里甘"
L["Mari Stonehand"] = "玛里·石拳"
L["Maria Lumere"] = "玛丽亚·卢米尔"
L["Martine Tramblay"] = "马丁·塔布雷"
L["Masat T'andr"] = "马萨特·坦德"
L["Master Chef Mouldier"] = "大厨师莫迪尔"
L["Mathar G'ochar"] = "玛萨·格卡尔"
L["Mavralyn"] = "马弗拉林"
L["Mazk Snipeshot"] = "玛兹克·斯奈普沙特"
L["Melaris"] = "梅拉瑞斯"
L["Micha Yance"] = "米沙·杨斯"
L["Millie Gregorian"] = "米利尔·格里高利"
L["Mishta"] = "米什塔"
L["Mixie Farshot"] = "米希·法索"
L["Montarr"] = "莫塔尔"
L["Muheru the Weaver"] = "编织者姆赫鲁"
L["Muuran"] = "穆尔兰"
L["Mythrin'dir"] = "迈斯林迪尔"
L["Naal Mistrunner"] = "纳尔·迷雾行者"
L["Namdo Bizzfizzle"] = "纳姆杜"
L["Nandar Branson"] = "南达·布拉森"
L["Narkk"] = "纳尔克"
L["Nasmara Moonsong"] = "纳丝玛拉·月歌"
L["Nata Dawnstrider"] = "纳塔·黎明行者"
L["Neal Allen"] = "尼尔·奥雷"
L["Neii"] = "奈伊"
L["Nergal"] = "奈尔加"
L["Nerrist"] = "耐里斯特"
L["Nessa Shadowsong"] = "尼莎·影歌"
L["Nina Lightbrew"] = "妮娜·莱特布鲁"
L["Nioma"] = "尼奥玛"
L["Nula the Butcher"] = "屠夫努尔拉"
L["Nyoma"] = "奈欧玛"
L["Ogg'marr"] = "奥克玛尔"
L["Otho Moji'ko"] = "奥索·莫吉克"
L["Outfitter Eric"] = "埃瑞克"
L["Phea"] = "菲恩"
L["Plugger Spazzring"] = "普拉格"
L["Pratt McGrubben"] = "普拉特·马克格鲁比"
L["Qia"] = "琦亚"
L["Quartermaster Davian Vaclav"] = "军需官达维安·瓦克拉弗"
L["Quartermaster Jaffrey Noreliqe"] = "军需官亚弗雷·诺雷里克"
L["Quelis"] = "奎尔里斯"
L["Ranik"] = "拉尼克"
L["Rann Flamespinner"] = "拉恩·火翼"
L["Rartar"] = "拉尔塔"
L["Rathis Tomber"] = "拉提斯·托博尔"
L["Rikqiz"] = "雷克奇兹"
L["Rizz Loosebolt"] = "里兹·飞矢"
L["Rohok"] = "罗霍克"
L["Ronald Burch"] = "罗纳德·伯奇"
L["Rungor"] = "伦格尔"
L["Ruppo Zipcoil"] = "鲁普·火油"
L["Saenorion"] = "塞诺里奥"
L["Seer Janidi"] = "先知亚尼迪"
L["Sewa Mistrunner"] = "苏瓦·迷雾行者"
L["Shadi Mistrunner"] = "沙迪·迷雾行者"
L["Shankys"] = "山吉斯"
L["Sheendra Tallgrass"] = "希恩德拉·深草"
L["Shen'dralar Provisioner"] = "辛德拉圣职者"
L["Sheri Zipstitch"] = "舍瑞·希普斯迪"
L["Sid Limbardi"] = "希德·利巴迪"
L["Skreah"] = "斯克雷亚"
L["Soolie Berryfizz"] = "苏雷·浆泡"
L["Sovik"] = "索维克"
L["Stuart Fleming"] = "斯图亚特·弗雷明"
L["Sumi"] = "苏米"
L["Super-Seller 680"] = "超级商人680型"
L["Supply Officer Mills"] = "供给官米尔斯"
L["Tamar"] = "达玛尔"
L["Tansy Puddlefizz"] = "坦斯·泥泡"
L["Tarban Hearthgrain"] = "塔班·熟麦"
L["Tari'qa"] = "塔里查"
L["Tatiana"] = "塔蒂亚娜"
L["Thaddeus Webb"] = "萨德乌斯·韦伯"
L["Tharynn Bouden"] = "萨瑞恩·博丁"
L["Thomas Yance"] = "托马斯·杨斯"
L["Tilli Thistlefuzz"] = "提尔利·草须"
L["Truk Wildbeard"] = "特鲁克·蛮鬃"
L["Tunkk"] = "吞克"
L["Ulthaan"] = "尤萨恩"
L["Ulthir"] = "尤希尔"
L["Uriku"] = "乌利库"
L["Uthok"] = "尤索克"
L["Vaean"] = "维安"
L["Valdaron"] = "瓦尔达隆"
L["Veenix"] = "维尼克斯"
L["Vendor-Tron 1000"] = "贸易机器人1000型"
L["Vharr"] = "维哈尔"
L["Viggz Shinesparked"] = "维格兹·沙斯巴克"
L["Vivianna"] = "薇薇安娜"
L["Vizzklick"] = "维兹格里克"
L["Vodesiin"] = "沃德辛"
L["Wenna Silkbeard"] = "温纳·银须"
L["Werg Thickblade"] = "维尔格·厚刃"
L["Wik'Tar"] = "维克塔"
L["Wind Trader Lathrai"] = "星界商人拉斯莱"
L["Wrahk"] = "瓦尔克"
L["Wulan"] = "乌兰"
L["Wunna Darkmane"] = "温纳·黑鬃"
L["Xandar Goodbeard"] = "山达·细须"
L["Xen'to"] = "克森图"
L["Xizk Goodstitch"] = "希兹克·古斯提"
L["Xizzer Fizzbolt"] = "希兹尔·菲兹波特"
L["Yatheon"] = "亚瑟恩"
L["Yonada"] = "犹纳达"
L["Yuka Screwspigot"] = "尤卡·斯库比格特"
L["Yurial Soulwater"] = "尤利安·魂水"
L["Zan Shivsproket"] = "萨恩·刀链"
L["Zannok Hidepiercer"] = "扎诺克"
L["Zansoa"] = "詹苏尔"
L["Zaralda"] = "萨拉尔达"
L["Zarena Cromwind"] = "萨瑞娜·克罗姆温德"
L["Zixil"] = "吉克希尔"
L["Zorbin Fandazzle"] = "索尔宾·范达瑟"
L["Zurai"] = "祖莱"
L["Narj Deepslice"] = "纳尔基·长刀"
L["Fazu"] = "法苏"
L["Zargh"] = "扎尔夫"
L["Smudge Thunderwood"] = "斯穆德·雷木"
L["Sassa Weldwell"] = "萨莎·焊井"

]]--